##########################################
########## COMPONENTS ####################
##########################################
# sensor:

#-----------------------------------------------------#

automation:
##########################################
########## NOTIFICATIONS #################
##########################################

  - alias: motion_detected_no_resident_home
    trigger:
    - platform: state
      entity_id: binary_sensor.entertainment_center_motion_sensor
      from: 'off'
      to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.var_residents_home
        state: "off"
    action:
      - service: script.notify2
        data_template:
          telegram_message: |
            *ALERT!* Motion Detected! No Residents are home!!
            *debug_informtion:*
            {{ trigger.entity_id }} = {{ trigger.to_state.state }}
            var_residents_home = {{ states.input_boolean.var_residents_home.state }}


##########################################
########## AUTOMATIONS ###################
##########################################
  #**********  All Residents Home/Away Automations  ***********#
  - alias: all_residents_away_automations
    trigger:
      - platform: state
        entity_id: input_boolean.var_residents_home
        from: 'on'
        to: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.option_mode_away


  - alias: any_resident_home_automation
    trigger:
      - platform: state
        entity_id: input_boolean.var_residents_home
        from: 'off'
        to: 'on'
    action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.option_mode_normal
    - service: script.scene2
      data:
        rooms: 'all'
        scene_name: 'day_bright'
        transition: 1
    - delay: "00:05:00"
    - service: script.scene2
      data_template:
        rooms: 'all'
        scene_name: '{{ states.input_select.var_lks_timebased.state }}'
        transition: 5

#-----------------------------------------------------#

# script:
##########################################
########## SCRIPTS #######################
##########################################

#-----------------------------------------------------#

# input_boolean:
##########################################
########## BACKEND #######################
##########################################

##########################################
########## OPTIONS #######################
##########################################

##########################################
########## CONFIG ########################
##########################################

#-----------------------------------------------------#

# homeassistant:
#   customize:
##########################################
########## EMULATED HUE ##################
##########################################
    # input_boolean.template:
    #   emulated_hue: true
    #   emulated_hue_name: "Template Name"

#-----------------------------------------------------#

group:
##########################################
############### GROUPS ###################
##########################################

##########################################
############### AUTO-GROUPS ##############
##########################################
  automation_residents:
    entities:
      - automation.all_residents_away_automations
      - automation.any_resident_home_automation
      - automation.motion_detected_no_resident_home

#   backend_residents:
#     entities:
#       - input_boolean.

#   config_residents:
#     entities:
#       - input_boolean.

#   hidden_residents:
#     entities:
#       - input_boolean.

#   options_residents:
#     entities:
#       - input_boolean.

#   script_residents:
#     entities:
#       - script.
