homeassistant:
  customize:
    script.scene2_chill:
      entity_picture: http://192.168.1.3:8123/local/icons/chill.png

script:
##########################################
########## LIVING ROOM ###################
##########################################
  scene2_chill:
    sequence:
      - service: script.turn_off
        entity_id: script.scene2
      - service: script.scene2
        data_template:
          scene_name: 'chill'
          rooms: "all"
          transition: 1

  scene2_chill_livingroom:
    sequence:
      - service: light.turn_on
        data_template:
          entity_id:
            - light.living_room_overhead
            - light.tv_overhead_right
            - light.tv_overhead_left

          brightness: 196
          rgb_color: [98, 2, 176]
          color_temp: 208
          transition: '{{transition}}'

      - service: light.turn_on
        data_template:
          entity_id:
            - light.end_table_left
            - light.end_table_right
          brightness: 132
          rgb_color: [2, 111, 7]
          color_temp: 207
          transition: '{{transition}}'

      - service: light.turn_on
        data_template:
          entity_id:
            - light.tv_floor_left
            - light.tv_floor_right
          brightness: 252
          rgb_color: [5, 241, 52]
          color_temp: 209
          transition: '{{transition}}'

      - service: light.turn_on
        data_template:
          entity_id:
            - light.tables_led_strip
          brightness: 45
          rgb_color: [72, 6, 153]
          color_temp: 207
          transition: '{{transition}}'

      - service: light.turn_on
        data_template:
          entity_id:
            - light.entertainment_center_led_strip
          brightness: 70
          rgb_color: [98, 2, 176]
          color_temp: 207
          transition: '{{transition}}'

      - service: input_select.select_option
        data:
          entity_id:
            - input_select.tables_led_effect
            - input_select.entertainment_center_led_effect
          option: 'Static'

      - service: input_select.select_option
        data:
          entity_id: input_select.var_lks_livingroom
          option: 'chill'


##########################################
########## OFFICE ########################
##########################################
  scene2_chill_office:
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: light.office_right
          brightness: 174
          rgb_color: [72, 6, 153]
          color_temp: 208
          transition: '{{transition}}'
      - service: light.turn_on
        data_template:
          entity_id:
            - light.office_center
            - light.office_left
          brightness: 133
          rgb_color: [4, 113, 17]
          color_temp: 207
          transition: '{{transition}}'

      - service: light.turn_on
        data_template:
          entity_id: light.office_led_strip
          brightness: 45
          rgb_color: [72, 6, 153]
          color_temp: 207
          transition: '{{transition}}'
      - service: input_select.select_option
        data:
          entity_id: input_select.office_led_effect
          option: 'Static'

      - service: input_select.select_option
        data:
          entity_id: input_select.var_lks_office
          option: 'chill'


##########################################
########## KITCHEN #######################
##########################################
  scene2_chill_kitchen:
    sequence:

      # Kitchen Light Motion On
      - service_template: >
          {% if states.input_boolean.var_kitchen_motion_on.state == "on" %}
            script.kitchen_lights_on
          {% else %}
            script.scene2_do_nothing
          {% endif %}
      - condition: state
        entity_id: input_boolean.var_kitchen_motion_on
        state: 'off'

      # Regular Scene
      - service: light.turn_on
        data_template:
          entity_id:
            - light.kitchen_left
          brightness: 152
          rgb_color: [3, 132, 12]
          color_temp: 207
          transition: '{{transition}}'

      - service: light.turn_on
        data_template:
          entity_id:
            - light.kitchen_right
          brightness: 126
          rgb_color: [43, 0, 106]
          color_temp: 207
          transition: '{{transition}}'

      - service: light.turn_on
        data_template:
          entity_id: light.kitchen_led_strip
          brightness: 45
          rgb_color: [72, 6, 153]
          color_temp: 207
          transition: '{{transition}}'
      - service: input_select.select_option
        data:
          entity_id: input_select.kitchen_led_effect
          option: 'Static'

      - service: input_select.select_option
        data:
          entity_id: input_select.var_lks_kitchen
          option: 'chill'


##########################################
########## BEDROOM #######################
##########################################
  scene2_chill_bedroom:
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: light.sonoff_silver_lamp

      - service: light.turn_on
        data_template:
          entity_id: light.bedroom_led_strip
          brightness: 45
          rgb_color: [2, 234, 0]
          color_temp: 207
          transition: '{{transition}}'
      - service: input_select.select_option
        data:
          entity_id: input_select.bedroom_led_effect
          option: 'Static'

      - service: input_select.select_option
        data:
          entity_id: input_select.var_lks_bedroom
          option: 'chill'
