homeassistant:
  customize:
    script.scene2_day:
      entity_picture: http://192.168.1.3:8123/local/icons/day.png

script:
##########################################
########## LIVING ROOM ###################
##########################################
  scene2_day:
    sequence:
      - service: script.turn_off
        entity_id: script.scene2
      - service: script.scene2
        data_template:
          scene_name: 'day'
          rooms: "all"
          transition: 1

  scene2_day_livingroom:
    sequence:
      - service: light.turn_on
        data_template:
          entity_id:
            - light.living_room_overhead
            - light.tv_overhead_right
            - light.tv_overhead_left
            - light.end_table_left
            - light.end_table_right
            - light.tv_floor_left
            - light.tv_floor_right
          brightness: 255
          color_temp: 200
          transition: '{{transition}}'

      - service: light.turn_off
        data_template:
          entity_id:
            - light.tables_led_strip
            - light.entertainment_center_led_strip
          transition: '{{transition}}'

      - service: input_select.select_option
        data:
          entity_id:
            - input_select.tables_led_effect
            - input_select.entertainment_center_led_effect
          option: 'Static'

      - service: input_select.select_option
        data:
          entity_id: input_select.var_lks_livingroom
          option: 'day'


##########################################
########## OFFICE ########################
##########################################
  scene2_day_office:
    sequence:
      - service: light.turn_on
        data_template:
          entity_id:
            - light.office_right
            - light.office_center
            - light.office_left
          brightness: 255
          color_temp: 200
          transition: '{{transition}}'

      - service: light.turn_off
        data_template:
          entity_id: light.office_led_strip
          transition: '{{transition}}'

      - service: input_select.select_option
        data:
          entity_id: input_select.office_led_effect
          option: 'Static'

      - service: input_select.select_option
        data:
          entity_id: input_select.var_lks_office
          option: 'day'


##########################################
########## KITCHEN #######################
##########################################
  scene2_day_kitchen:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.var_lks_kitchen
          option: 'day'

      # Kitchen Light Motion On
      - service_template: >
          {% if states.input_boolean.var_kitchen_motion_on.state == "on" %}
            script.kitchen_lights_on
          {% else %}
            script.scene2_do_nothing
          {% endif %}
      - condition: state
        entity_id: input_boolean.var_kitchen_motion_on
        state: 'off'

      # Regular Scene
      - service: light.turn_off
        data_template:
          entity_id:
            - light.kitchen_left
            - light.kitchen_right
            - light.kitchen_led_strip
          transition: '{{transition}}'

      - service: input_select.select_option
        data:
          entity_id: input_select.kitchen_led_effect
          option: 'Static'




##########################################
########## BEDROOM #######################
##########################################
  scene2_day_bedroom:
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: light.sonoff_silver_lamp

      - service: light.turn_off
        data_template:
          entity_id: light.bedroom_led_strip
          transition: '{{transition}}'
      - service: input_select.select_option
        data:
          entity_id: input_select.bedroom_led_effect
          option: 'Static'

      - service: input_select.select_option
        data:
          entity_id: input_select.var_lks_bedroom
          option: 'day'

##########################################
############### GROUPS ###################
##########################################
group:
  hidden_scene2_day:
    entities:
      - script.scene2_day_bedroom
      - script.scene2_day_kitchen
      - script.scene2_day_livingroom
      - script.scene2_day_office
