homeassistant:
  customize:
    script.scene2_day_le:
      entity_picture: http://192.168.1.3:8123/local/icons/day_le.png

script:
##########################################
########## LIVING ROOM ###################
##########################################
  scene2_day_le:
    sequence:
      - service: script.turn_off
        entity_id: script.scene2
      - service: script.scene2
        data_template:
          scene_name: 'day_le'
          rooms: "all"
          transition: 1

  scene2_day_le_livingroom:
    sequence:
      - service: light.turn_on
        data_template:
          entity_id:
            - light.living_room_overhead
          brightness: 185
          color_temp: 200
          transition: '{{transition}}'

      - service: light.turn_on
        data_template:
          entity_id:
            - light.tv_overhead_right
            - light.tv_overhead_left
          brightness: 140
          color_temp: 200
          transition: '{{transition}}'

      - service: light.turn_off
        data_template:
          entity_id:
            - light.end_table_left
            - light.end_table_right
            - light.tv_floor_left
            - light.tv_floor_right
            - light.tables_led_strip
            - light.entertainment_center_led_strip
          transition: '{{transition}}'

      - service: input_select.select_option
        data:
          entity_id:
            - input_select.tables_led_effect
            - input_select.entertainment_center_led_effect
          option: 'Static'

      - service: input_text.set_value
        data:
          entity_id: input_text.var_lks_livingroom
          value: 'day_le'


##########################################
########## OFFICE ########################
##########################################
  scene2_day_le_office:
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: light.office_right
          brightness: 185
          color_temp: 200
          transition: '{{transition}}'
      - service: light.turn_on
        data_template:
          entity_id:
            - light.office_center
            - light.office_left
          brightness: 140
          color_temp: 200
          transition: '{{transition}}'

      - service: light.turn_off
        data_template:
          entity_id: light.office_led_strip
          transition: '{{transition}}'
      - service: input_select.select_option
        data:
          entity_id: input_select.office_led_effect
          option: 'Static'

      - service: input_text.set_value
        data:
          entity_id: input_text.var_lks_office
          value: 'day_le'


##########################################
########## KITCHEN #######################
##########################################
  scene2_day_le_kitchen:
    sequence:
      - service: input_text.set_value
        data:
          entity_id: input_text.var_lks_kitchen
          value: 'day_le'

      # Kitchen Light Motion On
      - service_template: >
          {% if states.input_boolean.var_kitchen_motion_on.state == "on" %}
            script.kitchen_lights_on
          {% else %}
            script.scene2_do_nothing
          {% endif %}
      - condition: state
        entity_id: input_boolean.var_kitchen_motion_on
        state: 'off'

      # Regular Scene
      - service: light.turn_off
        data_template:
          entity_id:
            - light.kitchen_left
            - light.kitchen_right
            - light.kitchen_led_strip
          transition: '{{transition}}'

      - service: input_select.select_option
        data:
          entity_id: input_select.kitchen_led_effect
          option: 'Static'




##########################################
########## BEDROOM #######################
##########################################
  scene2_day_le_bedroom:
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: light.sonoff_silver_lamp

      - service: light.turn_off
        data_template:
          entity_id: light.bedroom_led_strip
          transition: '{{transition}}'

      - service: input_select.select_option
        data:
          entity_id: input_select.bedroom_led_effect
          option: 'Static'

      - service: input_text.set_value
        data:
          entity_id: input_text.var_lks_bedroom
          value: 'day_le'

##########################################
############### GROUPS ###################
##########################################
group:
  hidden_scene2_day_le:
    entities:
      - script.scene2_day_le_bedroom
      - script.scene2_day_le_kitchen
      - script.scene2_day_le_livingroom
      - script.scene2_day_le_office
