homeassistant:
  customize:
    script.scene2_night:
      entity_picture: http://192.168.1.3:8123/local/icons/night.png

script:
##########################################
########## LIVING ROOM ###################
##########################################
  scene2_night:
    sequence:
      - service: script.scene2
        data_template:
          scene_name: 'night'
          rooms: "all"
          transition: 1

  scene2_night_livingroom:
    sequence:
      - service: light.turn_on
        data_template:
          entity_id:
            - light.living_room_overhead
          brightness: 174
          rgb_color: [173, 173, 173]
          color_temp: 191
          transition: '{{transition}}'

      - service: light.turn_on
        data_template:
          entity_id:
            - light.end_table_left
            - light.end_table_right
          brightness: 80
          rgb_color: [80, 80, 80]
          color_temp: 191
          transition: '{{transition}}'

      - service: light.turn_on
        data_template:
          entity_id:
            - light.tv_overhead_right
            - light.tv_overhead_left
            - light.tv_floor_left
            - light.tv_floor_right
          brightness: 102
          rgb_color: [101, 101, 101]
          color_temp: 191
          transition: '{{transition}}'

      - service: light.turn_off
        data_template:
          entity_id:
            - light.tables_led_strip
            - light.entertainment_center_led_strip
          transition: '{{transition}}'
      - service: input_select.select_option
        data:
          entity_id:
            - input_select.tables_led_effect
            - input_select.entertainment_center_led_effect
          option: 'Static'

      - service: input_select.select_option
        data:
          entity_id: input_select.var_lks_livingroom
          option: 'night'


##########################################
########## OFFICE ########################
##########################################
  scene2_night_office:
    sequence:
      - service: light.turn_on
        data_template:
          entity_id:
            - light.office_right
            - light.office_center
            - light.office_left
          brightness: 102
          rgb_color: [101, 101, 101]
          color_temp: 191
          transition: '{{transition}}'

      - service: light.turn_off
        data_template:
          entity_id: light.office_led_strip
          transition: '{{transition}}'
      - service: input_select.select_option
        data:
          entity_id: input_select.office_led_effect
          option: 'Static'

      - service: input_select.select_option
        data:
          entity_id: input_select.var_lks_office
          option: 'night'


##########################################
########## KITCHEN #######################
##########################################
  scene2_night_kitchen:
    sequence:

      # Kitchen Light Motion On
      - service_template: >
          {% if states.input_boolean.var_kitchen_motion_on.state == "on" %}
            script.kitchen_lights_on
          {% else %}
            script.script2_do_nothing
          {% endif %}
      - condition: state
        entity_id: input_boolean.var_kitchen_motion_on
        state: 'off'

      # Regular Scene
      - service: light.turn_off
        data_template:
          entity_id:
            - light.kitchen_left
            - light.kitchen_right
            - light.kitchen_led_strip
          transition: '{{transition}}'

      - service: input_select.select_option
        data:
          entity_id: input_select.kitchen_led_effect
          option: 'Static'

      - service: input_select.select_option
        data:
          entity_id: input_select.var_lks_kitchen
          option: 'night'


##########################################
########## BEDROOM #######################
##########################################
  scene2_night_bedroom:
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: light.sonoff_silver_lamp

      - service: light.turn_off
        data_template:
          entity_id: light.bedroom_led_strip
          transition: '{{transition}}'
          
      - service: input_select.select_option
        data:
          entity_id: input_select.bedroom_led_effect
          option: 'Static'

      - service: input_select.select_option
        data:
          entity_id: input_select.var_lks_bedroom
          option: 'night'
