homeassistant:
  customize:
    script.scene2_night_blue:
      entity_picture: http://192.168.1.3:8123/local/icons/night_blue.png

script:
##########################################
########## LIVING ROOM ###################
##########################################
  scene2_night_blue:
    sequence:
      - service: script.turn_off
        entity_id: script.scene2
      - service: script.scene2
        data_template:
          scene_name: 'night_blue'
          rooms: "all"
          transition: 1

  scene2_night_blue_livingroom:
    sequence:
      - service: light.turn_on
        data_template:
          entity_id:
            - light.living_room_overhead
            - light.tv_overhead_right
            - light.tv_overhead_left
          brightness: 180
          rgb_color: [129, 129, 129]
          color_temp: 250
          transition: '{{transition}}'

      - service: light.turn_on
        data_template:
          entity_id:
            - light.end_table_left
            - light.end_table_right
          brightness: 106
          rgb_color: [0, 105, 104]
          color_temp: 207
          transition: '{{transition}}'

      - service: light.turn_on
        data_template:
          entity_id:
            - light.tv_floor_left
            - light.tv_floor_right
          brightness: 125
          rgb_color: [0, 105, 104]
          color_temp: 207
          transition: '{{transition}}'

      - service: light.turn_on
        data_template:
          entity_id:
            - light.tables_led_strip
          brightness: 45
          rgb_color: [91, 0, 221]
          color_temp: 207
          transition: '{{transition}}'

      - service: light.turn_on
        data_template:
          entity_id:
            - light.entertainment_center_led_strip
          brightness: 90
          rgb_color: [91, 0, 221]
          color_temp: 207
          transition: '{{transition}}'

      - service: input_select.select_option
        data:
          entity_id:
            - input_select.tables_led_effect
            - input_select.entertainment_center_led_effect
          option: 'Static'

      - service: input_select.select_option
        data:
          entity_id: input_select.var_lks_livingroom
          option: 'night_blue'


##########################################
########## OFFICE ########################
##########################################
  scene2_night_blue_office:
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: light.office_right
          brightness: 180
          rgb_color: [101, 101, 101]
          color_temp: 285
          transition: '{{transition}}'
      - service: light.turn_on
        data_template:
          entity_id:
            - light.office_center
            - light.office_left
          brightness: 75
          rgb_color: [0, 105, 104]
          color_temp: 207
          transition: '{{transition}}'

      - service: light.turn_on
        data_template:
          entity_id: light.office_led_strip
          brightness: 45
          rgb_color: [91, 0, 221]
          color_temp: 207
          transition: '{{transition}}'
      - service: input_select.select_option
        data:
          entity_id: input_select.office_led_effect
          option: 'Static'

      - service: input_select.select_option
        data:
          entity_id: input_select.var_lks_office
          option: 'night_blue'


##########################################
########## KITCHEN #######################
##########################################
  scene2_night_blue_kitchen:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.var_lks_kitchen
          option: 'night_blue'
          
      # Kitchen Light Motion On
      - service_template: >
          {% if states.input_boolean.var_kitchen_motion_on.state == "on" %}
            script.kitchen_lights_on
          {% else %}
            script.scene2_do_nothing
          {% endif %}
      - condition: state
        entity_id: input_boolean.var_kitchen_motion_on
        state: 'off'

      # Regular Scene
      - service: light.turn_on
        data_template:
          entity_id:
            - light.kitchen_left
            - light.kitchen_right
          brightness: 50
          rgb_color: [0, 105, 104]
          color_temp: 207
          transition: '{{transition}}'

      - service: light.turn_on
        data_template:
          entity_id: light.kitchen_led_strip
          brightness: 45
          rgb_color: [91, 0, 221]
          color_temp: 207
          transition: '{{transition}}'
      - service: input_select.select_option
        data:
          entity_id: input_select.kitchen_led_effect
          option: 'Static'




##########################################
########## BEDROOM #######################
##########################################
  scene2_night_blue_bedroom:
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: light.sonoff_silver_lamp

      - service: light.turn_on
        data_template:
          entity_id: light.bedroom_led_strip
          brightness: 45
          rgb_color: [91, 0, 221]
          color_temp: 207
          transition: '{{transition}}'
      - service: input_select.select_option
        data:
          entity_id: input_select.bedroom_led_effect
          option: 'Static'

      - service: input_select.select_option
        data:
          entity_id: input_select.var_lks_bedroom
          option: 'night_blue'
