homeassistant:
  customize:
    script.scene2_prework_purple:
      entity_picture: http://192.168.1.3:8123/local/icons/prework_purple.png

script:
##########################################
########## LIVING ROOM ###################
##########################################
  scene2_prework_purple:
    sequence:
      - service: script.turn_off
        entity_id: script.scene2
      - service: script.scene2
        data_template:
          scene_name: 'prework_purple'
          rooms: "all"
          transition: 1

  scene2_prework_purple_livingroom:
    sequence:
      - service: light.turn_on
        data_template:
          entity_id:
            - light.living_room_overhead
            - light.tv_overhead_right
            - light.tv_overhead_left
            - light.end_table_left
            - light.end_table_right
          brightness: 255
          color_temp: 200
          transition: '{{transition}}'

      - service: light.turn_on
        data_template:
          entity_id:
            - light.tv_floor_left
            - light.tv_floor_right
          brightness: 155
          rgb_color: [68,0,155]

      - service: light.turn_on
        data_template:
          entity_id:
            - light.tables_led_strip
            - light.entertainment_center_led_strip
          brightness: 216
          rgb_color: [68,0,155]
          transition: '{{transition}}'

      - service: input_select.select_option
        data:
          entity_id:
            - input_select.tables_led_effect
            - input_select.entertainment_center_led_effect
          option: 'Static'

      - service: input_text.set_value
        data:
          entity_id: input_text.var_lks_livingroom
          value: 'prework_purple'


##########################################
########## OFFICE ########################
##########################################
  scene2_prework_purple_office:
    sequence:
      - service: light.turn_on
        data_template:
          entity_id:
            - light.office_right
            - light.office_center
            - light.office_left
          brightness: 255
          color_temp: 200
          transition: '{{transition}}'

      - service: light.turn_on
        data_template:
          entity_id: light.office_led_strip
          brightness: 216
          rgb_color: [68,0,155]
          transition: '{{transition}}'

      - service: input_select.select_option
        data:
          entity_id: input_select.office_led_effect
          option: 'Static'

      - service: input_text.set_value
        data:
          entity_id: input_text.var_lks_office
          value: 'prework_purple'


##########################################
########## KITCHEN #######################
##########################################
  scene2_prework_purple_kitchen:
    sequence:
      - service: input_text.set_value
        data:
          entity_id: input_text.var_lks_kitchen
          value: 'prework_purple'

      # Kitchen Light Motion On
      - service_template: >
          {% if states.input_boolean.var_kitchen_motion_on.state == "on" %}
            script.kitchen_lights_on
          {% else %}
            script.scene2_do_nothing
          {% endif %}
      - condition: state
        entity_id: input_boolean.var_kitchen_motion_on
        state: 'off'

      # Regular Scene
      - service: light.turn_on
        data_template:
          entity_id:
            - light.kitchen_left
            - light.kitchen_right
          brightness: 255
          color_temp: 200
          transition: '{{transition}}'

      - service: light.turn_on
        data_template:
          entity_id: light.kitchen_led_strip
          brightness: 216
          rgb_color: [68,0,155]
          transition: '{{transition}}'

      - service: input_select.select_option
        data:
          entity_id: input_select.kitchen_led_effect
          option: 'Static'




##########################################
########## BEDROOM #######################
##########################################
  scene2_prework_purple_bedroom:
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: light.sonoff_silver_lamp

      - service: light.turn_on
        data_template:
          entity_id: light.bedroom_led_strip
          brightness: 216
          rgb_color: [68,0,155]
          transition: '{{transition}}'

      - service: input_select.select_option
        data:
          entity_id: input_select.bedroom_led_effect
          option: 'Static'

      - service: input_text.set_value
        data:
          entity_id: input_text.var_lks_bedroom
          value: 'prework_purple'


##########################################
########## GROUPS ########################
##########################################
group:
  hidden_prework_purple:
    entities:
    - script.scene2_prework_purple
    - script.scene2_prework_purple_livingroom
    - script.scene2_prework_purple_office
    - script.scene2_prework_purple_kitchen
    - script.scene2_prework_purple_bedroom
