##########################################
########## vHOME v0.11.6 ################
##########################################
homeassistant:
  name: vHome
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: !secret homeassistant_unit_system
  time_zone: !secret homeassistant_time_zone
  customize: !include_dir_merge_named customize
  packages: !include_dir_named packages

http:
  api_password: !secret http_api_password
  base_url: !secret http_base_url
  trusted_networks: !secret http_trusted_networks
  ip_ban_enabled: True
  login_attempts_threshold: 5

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  username: !secret mqtt_username
  password: !secret mqtt_password
  keepalive: 60

emulated_hue:
  type: alexa
  host_ip: !secret emulated_hue_host_ip
  listen_port: !secret emulated_hue_port
  off_maps_to_on_domains:
    - script
  expose_by_default: true
  exposed_domains:
    # - light

# feedreader:
#   urls:
#     - https://home-assistant.io/atom.xml

influxdb:
  host: !secret influxdb_host
  port: !secret influxdb_port
  database: !secret influxdb_database

updater:
  reporting: False
discovery:
conversation:
history:
config:
recorder:
#   db_url: !secret db_url
  purge_interval: 1
  purge_keep_days: 3
logger: # Log Severities: notset, debug, info, warn, warning, error, fatal, critical
  default: warning  # Can also change via input_select
  # logs:
  #   homeassistant.components.mqtt: debug

sun:
# ios:
scene: !include_dir_list scene
group: !include_dir_merge_named group


frontend:
  themes: !include_dir_merge_named themes/
