##########################################
########## vHOME v0.9.10 #################
##########################################
homeassistant:
  name: vHome
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: !secret homeassistant_unit_system
  time_zone: !secret homeassistant_time_zone
  customize: !include_dir_merge_named customize
  packages: !include_dir_named packages

http:
  api_password: !secret http_api_password
  base_url: http://192.168.1.3:8123
  trusted_networks:
    - 192.168.1.0/24
  ip_ban_enabled: True
  login_attempts_threshold: 5

mqtt:
  broker: 192.168.1.3
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password
  keepalive: 60

emulated_hue:
  type: alexa
  host_ip: 192.168.1.3
  listen_port: 8300
  off_maps_to_on_domains:
    - script
  expose_by_default: true
  exposed_domains:
    # - light

# feedreader:
#   urls:
#     - https://home-assistant.io/atom.xml

influxdb:
  host: 192.168.1.3
  port: 8086
  database: home_assistant

updater:
  reporting: False
discovery:
conversation:
history:
config:
recorder:
#   db_url: !secret db_url
  purge_interval: 1
  purge_keep_days: 3
logger: # Log Severities: notset, debug, info, warn, warning, error, fatal, critical
  default: warning  # Can also change via input_select
  # logs:
  #   homeassistant.components.mqtt: debug

sun:
# ios:
scene: !include_dir_list scene
group: !include_dir_merge_named group


frontend:
  themes: !include_dir_merge_named themes/
