##########################################
########## vHOME v0.4.20 #################
##########################################
homeassistant:
  name: vHome
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: !secret homeassistant_unit_system
  time_zone: !secret homeassistant_time_zone
  customize: !include_dir_merge_named customize
  packages: !include_dir_named packages

http:
  api_password: !secret http_api_password
  base_url: http://192.168.1.3:8123
  trusted_networks:
    - 192.168.1.41
    - 192.168.1.43
    - 192.168.1.44

mqtt:
  broker: 192.168.1.3
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password
  keepalive: 60

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

tts:
  - platform: google
    cache: true
    time_memory: 300
#
emulated_hue:
  type: alexa
  host_ip: 192.168.1.3
  listen_port: 8300
  expose_by_default: true
  exposed_domains:
    - light

feedreader:
  urls:
    - https://home-assistant.io/atom.xml

influxdb:
  host: 192.168.1.80
  port: 8086
  database: home_assistant

frontend:
updater:
discovery:
conversation:
history:
config:
recorder:
  purge_days: 14
logger: # Log Severities: notset, debug, info, warn, warning, error, fatal, critical
  default: warning  # Can also change via input_select
  # logs:
  #   homeassistant.components.mqtt: debug
logbook:
  exclude:
    entities:
      - group.ambient_lights
      - script.call_last_known_scene
      - script.set_var_last_known_scene
      - script.set_var_last_known_scene2
      - binary_sensor.entertainment_motion_sensor
      - binary_sensor.kitchen_motion_sensor
      - binary_sensor.bedroom_motion_sensor
      - binary_sensor.sink_motion_sensor
    domains:
      - light


sun:
ios:
scene: !include_dir_list scene
group: !include_dir_merge_named group
