##########################################
########## COMPONENTS ####################
##########################################
# sensor:

#-----------------------------------------------------#

automation:
##########################################
########## NOTIFICATIONS #################
##########################################

##########################################
########## AUTOMATIONS ###################
##########################################
## Turn on Alarm
  - alias: morning_alarm_timebased_turn_on
    trigger:
      - platform: time
        minutes: '/1'
        seconds: 00
    condition:
      - condition: template
        value_template: '{{ states.sensor.time.state | string == states.input_select.option_morning_alarm_time.state | string  }}'
      - condition: state
        entity_id: input_boolean.option_morning_alarm
        state: 'on'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.var_morning_alarm_on
      - delay: "00:10:00"
      - service: script.morning_alarm_turn_on

      - condition: state
        entity_id: input_boolean.option_morning_alarm2
        state: 'on'
      - delay: "00:10:00"
      - condition: state
        entity_id: input_boolean.var_morning_alarm_on
        state: 'off'
      - service: input_boolean.turn_on
        entity_id: input_boolean.var_morning_alarm_on
      - delay: "00:40:00"
      - service: script.morning_alarm_turn_on



## Turn off Alarm at after 1 hour
  - alias: morning_alarm_motion_turn_off_1hr
    trigger:
      - platform: state
        entity_id: input_boolean.var_morning_alarm_on
        to: 'on'
        for:
          hours: 1
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_morning_alarm_on
      - service: script.morning_alarm_turn_off
      - service: script.turn_off
        entity_id: script.morning_alarm_turn_on
      - service: script.turn_off
        entity_id: script.morning_alarm_turn_off

## Turn off Alarm at after motion detected in Office, Living Room, or Kitchen
  - alias: morning_alarm_motion_turn_off
    trigger:
      - platform: state
        entity_id: binary_sensor.entertainment_center_motion_sensor
      - platform: state
        entity_id: binary_sensor.kitchen_motion_sensor
      - platform: state
        entity_id: input_boolean.var_desktop_computer_on
      - platform: state
        entity_id: input_boolean.var_desktop_computer_on
        to: 'on'
        for:
          minutes: 15
      # - platform: state
      #   entity_id: binary_sensor.office_motion_sensor
    condition:
      - condition: state
        entity_id: input_boolean.var_morning_alarm_on
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_morning_alarm_on

  - alias: morning_alarm_motion_turn_off_flash_cyan
    trigger:
      - platform: state
        entity_id: input_boolean.var_morning_alarm_on
        from: 'on'
        to: 'off'
    action:
      - service: script.notify2
        data:
          flash_color: "cyan"
          entity_id: group.timebased_hourly_flash_lights

#-----------------------------------------------------#

##########################################
########## SCRIPTS #######################
##########################################
script:
  morning_alarm_turn_on:
    sequence:
    - service: script.turn_off
      entity_id: script.morning_alarm_turn_off
    - condition: state
      entity_id: input_boolean.var_morning_alarm_on
      state: 'on'
    - service: light.turn_on
      entity_id: light.sonoff_silver_lamp
    - service: light.turn_on
      entity_id: light.bedroom_led_strip
    - service: light.turn_on
      entity_id: light.office_led_strip
    - service: light.turn_on
      entity_id: light.tables_led_strip
    - service: light.turn_on
      entity_id: light.entertainment_center_led_strip
    - service: script.turn_on
      entity_id: script.morning_alarm_turn_off

  morning_alarm_turn_off:
    sequence:
    - service: script.turn_off
      entity_id: script.morning_alarm_turn_on
    - delay: "00:00:01"
    - service: light.turn_off
      entity_id: light.sonoff_silver_lamp
    - service: light.turn_off
      entity_id: light.bedroom_led_strip
    - service: light.turn_off
      entity_id: light.office_led_strip
    - service: light.turn_off
      entity_id: light.tables_led_strip
    - service: light.turn_off
      entity_id: light.entertainment_center_led_strip
    - delay: "00:00:01"
    - condition: state
      entity_id: input_boolean.var_morning_alarm_on
      state: 'on'
    - service: script.turn_on
      entity_id: script.morning_alarm_turn_on


#-----------------------------------------------------#

input_boolean:
##########################################
########## BACKEND #######################
##########################################
  var_morning_alarm_on: #state of alarm. The "OPTION" variable triggers if the alarm will run or not

##########################################
########## OPTIONS #######################
##########################################
  option_morning_alarm:
    name: "Morning Alarm"
    initial: on

  option_morning_alarm2:
    name: "2nd Morning Alarm"
    initial: on

input_select:
  option_morning_alarm_time:
    options:
      - "00:00"
      - "00:30"
      - "01:00"
      - "01:30"
      - "02:00"
      - "02:30"
      - "03:00"
      - "03:30"
      - "04:00"
      - "04:30"
      - "05:00"
      - "05:30"
      - "06:00"
      - "06:30"
      - "07:00"
      - "07:30"
      - "08:00"
      - "08:30"
      - "09:00"
      - "09:30"
      - "10:00"
      - "10:30"
      - "11:00"
      - "11:30"
      - "12:00"
      - "12:30"
      - "13:00"
      - "13:30"
      - "14:00"
      - "14:30"
      - "15:00"
      - "15:30"
      - "16:00"
      - "16:30"
      - "17:00"
      - "17:30"
      - "18:00"
      - "18:30"
      - "19:00"
      - "19:30"
      - "20:00"
      - "20:30"
      - "21:00"
      - "21:30"
      - "22:00"
      - "22:30"
      - "23:00"
      - "23:30"
    initial: "12:30"

##########################################
########## CONFIG ########################
##########################################

#-----------------------------------------------------#

homeassistant:
  customize:
##########################################
########## EMULATED HUE ##################
##########################################
    input_boolean.var_morning_alarm_on:
      emulated_hue: true
      emulated_hue_name: "Morning Alarm"

#-----------------------------------------------------#

group:
##########################################
############### GROUPS ###################
##########################################

##########################################
############### AUTO-GROUPS ##############
##########################################
  automation_alarms:
    entities:
      - automation.morning_alarm_timebased_turn_on
      - automation.morning_alarm_motion_turn_off_1hr
      - automation.morning_alarm_motion_turn_off
      - automation.morning_alarm_motion_turn_off_flash_cyan

  backend_alarm:
    entities:
      - input_boolean.var_morning_alarm_on

#   hidden_alarm:
#     entities:
#       - input_boolean.

  options_alarms:
    name: "Alarms"
    control: hidden
    entities:
      - input_boolean.option_morning_alarm
      - input_boolean.option_morning_alarm2
      - input_select.option_morning_alarm_time
      - input_boolean.option_timebased_telegram_summary

  script_alarms:
    entities:
      - script.morning_alarm_turn_on
      - script.morning_alarm_turn_off

#   sensor_alarms:
#     entities:
#       - sensor.
