## WORKFLOW:
## IFTTT triggers an POST to dweet.
## dweet sensor displays latest topic & message.
## dweetSensor is used to trigger HA automations.
#
#
## Topic = Type (ie. 'trump_tweet' or 'breaking_news')
## Message = Message Text

##########################################
########## COMPONENTS ####################
##########################################
ifttt:
  key: !secret ifttt_key

sensor:
  - platform: dweet
    name: dweet_vhome
    device: vhome
    value_template: '{{ value_json.message }}'
    scan_interval: 15

  - platform: template
    sensors:
      dweet_vhome_topic:
        value_template: "{% set dweet_vhome = states.sensor.dweet_vhome.state.split('::') %}{{ dweet_vhome[0] }}"
      dweet_vhome_message:
        value_template: >
          {% set dweet_vhome = states.sensor.dweet_vhome.state.split('::') %}
          {% set dweet_vhome_modified = dweet_vhome[1].split("—") %}
          {% set dweet_vhome_cleaned = dweet_vhome_modified[0].split('http') %}
          {{ dweet_vhome_cleaned[0] }}

#-----------------------------------------------------#

automation:
##########################################
########## NOTIFICATIONS #################
##########################################


##########################################
########## SPORTS NOTIFICAITONS ##########
##########################################
  - alias: nfl_game_start
    trigger:
      platform: state
      entity_id: sensor.dweet_vhome_topic
    condition:
      - condition: state
        entity_id: sensor.dweet_vhome_topic
        state: 'nfl_game_start'
    action:
      - service: script.notify2
        data_template:
          telegram_message: |
            *NFL GAME START:*
            {{ states.sensor.dweet_vhome_message.state }}
          tts_entity_id: group.tts_devices
          tts_sound: 'other/espn_alert.m4a'
          tts_pause_delay: "00:00:03"
          tts_message: |
            NFL Game Started! <break time=".9s" />
            {% set message = states.sensor.dweet_vhome_message.state | replace('"','') %}
            {% set sentence = message.split('.') %}
            {{ sentence[0] }}

  - alias: nfl_game_update
    trigger:
      platform: state
      entity_id: sensor.dweet_vhome_topic
    condition:
      condition: state
      entity_id: sensor.dweet_vhome_topic
      state: 'nfl_game_update'
    action:
      - service: script.notify2
        data_template:
          telegram_message: |
            *NFL GAME UPDATE:*
            {{ states.sensor.dweet_vhome_message.state }}
          tts_entity_id: group.tts_devices
          tts_sound: 'other/espn_alert.m4a'
          tts_pause_delay: "00:00:03"
          tts_message: |
            {% set message = states.sensor.dweet_vhome_message.state | replace('"','') %}
            {% set sentence = message.split('.') %}
            {{ sentence[0] }}

  - alias: nfl_game_end
    trigger:
      platform: state
      entity_id: sensor.dweet_vhome_topic
    condition:
      condition: state
      entity_id: sensor.dweet_vhome_topic
      state: 'nfl_game_end'
    action:
      - service: script.notify2
        data_template:
          telegram_message: |
            *NFL GAME ENDED:*
            {{ states.sensor.dweet_vhome_message.state }}
          tts_entity_id: group.tts_devices
          tts_sound: 'other/espn_alert.m4a'
          tts_pause_delay: "00:00:03"
          tts_message: |
            {% set message = states.sensor.dweet_vhome_message.state | replace('"','') %}
            {% set sentence = message.split('.') %}
            {{ sentence[0] }}

# ##########################################
# ########## TWITTER NOTIFICATIONS #########
# ##########################################
#
  - alias: breaking_news
    trigger:
      platform: state
      entity_id: sensor.dweet_vhome_topic
    condition:
      - condition: state
        entity_id: sensor.dweet_vhome_topic
        state: 'breaking_news'
      - condition: template
        value_template: '{% set msg = states.sensor.dweet_vhome_message.state %}{{ "BREAKING:" in msg or "JUST IN:" in msg or "UPDATE:" in msg or "HAPPENING NOW:" in msg or "BREAKING NEWS:" in msg}}'
    action:
      - service: script.notify2
        data_template:
          telegram_message: |
            *BREAKING NEWS:*
            {{ states.sensor.dweet_vhome_message.state }}
          tts_entity_id: group.tts_devices
          tts_sound: 'other/breaking_news.m4a'
          tts_pause_delay: "00:00:03"
          tts_message: |
            {% set dweet_vhome_message = states.sensor.dweet_vhome_message.state.split(":") %}
            {% set headline = dweet_vhome_message[0] | replace('"','') %}
            {% set message = dweet_vhome_message[1] | replace('"','') %}
            {{ headline }}: <break time=".9s" /> {{ message }}

  - alias: trump_tweet
    trigger:
      platform: state
      entity_id: sensor.dweet_vhome_topic
    condition:
      condition: state
      entity_id: sensor.dweet_vhome_topic
      state: 'trump_tweet'
    action:
      - service: script.notify2
        data_template:
          telegram_message: |
            *TRUMP:*
            {{ states.sensor.dweet_vhome_message.state }}
          tts_entity_id: group.tts_devices
          tts_sound: 'other/hailt_to_the_chief.m4a'
          tts_pause_delay: "00:00:03"
          tts_message: |
            President Trump just tweeted... <break time=".9s" /> {{ states.sensor.dweet_vhome_message.state | replace('"','') }}

##########################################
########## AUTOMATIONS ###################
##########################################

#-----------------------------------------------------#

##########################################
########## SCRIPTS #######################
##########################################
script:
  find_my_phone:
    alias: "Find My Phone"
    sequence:
    - service: ifttt.trigger
      data:
        event: "find_my_phone"
    - service: script.breathe_light
      data:
        breathe_color: "cyan"
        entity_id: group.all_lights
    - delay: "00:00:07"
    - service: script.flood_light
      data:
        flood_color: "white"
        entity_id: group.all_lights
        delay: "00:00:20"

#-----------------------------------------------------#

# input_boolean:
##########################################
########## BACKEND #######################
##########################################

##########################################
########## OPTIONS #######################
##########################################

##########################################
########## CONFIG ########################
##########################################

#-----------------------------------------------------#

homeassistant:
  customize:
##########################################
########## EMULATED HUE ##################
##########################################
    script.find_my_phone:
      emulated_hue: true
      emulated_hue_name: "find my phone"

#-----------------------------------------------------#

group:
##########################################
############### GROUPS ###################
##########################################

##########################################
############### AUTO-GROUPS ##############
##########################################
  automation_ifttt:
    entities:
      - automation.breaking_news
      - automation.nfl_game_start
      - automation.nfl_game_update
      - automation.nfl_game_end
      - automation.trump_tweet

  backend_ifttt:
    entities:
      - sensor.dweet_vhome
      - sensor.dweet_vhome_topic
      - sensor.dweet_vhome_message

#   config_ifttt:
#     entities:
#       - input_boolean.

#   hidden_ifttt:
#     entities:
#       - input_boolean.

#   options_ifttt:
#     entities:
#       - input_boolean.

  script_ifttt:
    entities:
      - script.find_my_phone
