##########################################
########## COMPONENTS ####################
##########################################
light:
  - platform: mqtt
    name: "Office LED Strip"
    command_topic: "device/office/led1/power"
    state_topic: "device/office/led1/power/pub"
    rgb_command_topic: "device/office/led1/color"
    rgb_state_topic: "device/office/led1/color/pub"
    brightness_command_topic: "device/office/led1/brightness"
    brightness_state_topic: "device/office/led1/brightness/pub"
    optimistic: false
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

binary_sensor:
  - platform: mqtt
    name: "Office Motion Sensor"
    state_topic: "device/office/pir1"
    device_class: motion
    payload_on: "1"
    payload_off: "0"

sensor:
  - platform: mqtt
    name: "Office Temperature"
    state_topic: "device/office/temperature"
    qos: 0
    unit_of_measurement: "ºF"
    expire_after: 900

  - platform: mqtt
    name: "Office Humidity"
    state_topic: "device/office/humidity"
    qos: 0
    unit_of_measurement: "%"
    expire_after: 900

#-----------------------------------------------------#

automation:
##########################################
########## NOTIFICATIONS #################
##########################################

##########################################
########## AUTOMATIONS ###################
##########################################
  - alias: office_leds_input_effect
    trigger:
      - platform: state
        entity_id: input_select.office_led_effect
    action:
      - service: mqtt.publish
        data_template:
          topic: "device/office/led1/effect"
          payload: >
            {% for opt in states.input_select.office_led_effect.attributes.options -%}
              {% if trigger.to_state.state | string == opt %}
                {{loop.index - 1}}
              {%endif%}
            {%- endfor -%}

  - alias: office_leds_animation_speed
    trigger:
      - platform: state
        entity_id: input_number.office_animation_speed
    action:
      - service: mqtt.publish
        data_template:
          topic: "device/office/led1/speed"
          payload: '{{ trigger.to_state.state | int }}'

#-----------------------------------------------------#

# script:
##########################################
########## SCRIPTS #######################
##########################################

#-----------------------------------------------------#

# input_boolean:
##########################################
########## BACKEND #######################
##########################################

##########################################
########## OPTIONS #######################
##########################################

##########################################
########## CONFIG #######################
##########################################
input_number:
  office_animation_speed:
    name: Office Animation Speed
    min: 0
    max: 255
    step: 5

input_select:
  office_led_effect:
    name: Office LED Effect
    options:
      - "Static"
      - "Blink"
      - "Breath"
      - "Color Wipe"
      - "Color Wipe Random"
      - "Random Color"
      - "Single Dynamic"
      - "Multi Dynamic"
      - "Rainbow"
      - "Rainbow Cycle"
      - "Scan"
      - "Dual Scan"
      - "Fade"
      - "Theater Chase"
      - "Theater Chase Rainbow"
      - "Running Lights"
      - "Twinkle"
      - "Twinkle Random"
      - "Twinkle Fade"
      - "Twinkle Fade Random"
      - "Sparkle"
      - "Flash Sparkle"
      - "Hyper Sparkle"
      - "Strobe"
      - "Strobe Rainbow"
      - "Multi Strobe"
      - "Blink Rainbow"
      - "Chase White"
      - "Chase Color"
      - "Chase Random"
      - "Chase Rainbow"
      - "Chase Flash"
      - "Chase Flash Random"
      - "Chase Rainbow White"
      - "Chase Blackout"
      - "Chase Blackout Rainbow"
      - "Color Sweep Random"
      - "Running Color"
      - "Running Red Blue"
      - "Running Random"
      - "Larson Scanner"
      - "Comet"
      - "Fireworks"
      - "Fireworks Random"
      - "Merry Christmas"
      - "Fire Flicker"
      - "Fire Flicker (soft)"
      - "vHome Wipe to Random"
      - "vHome Wipe to White"
      - "vHome Breathe"
    initial: "Static"

#-----------------------------------------------------#

# homeassistant:
#   customize:
##########################################
########## EMULATED HUE ##################
##########################################
    # input_boolean.template:
    #   emulated_hue: true
    #   emulated_hue_name: "Template Name"

#-----------------------------------------------------#

group:
##########################################
############### GROUPS ###################
##########################################

##########################################
############### AUTO-GROUPS ##############
##########################################
  automation_vcore_office:
    entities:
      - automation.office_leds_input_effect
      - automation.office_leds_animation_speed

#   backend_vcore_office:
#     entities:
#       - input_boolean.

  config_vcore_office:
    entities:
      - input_number.office_leds_animation_speed
      - input_select.office_led_effect

#   hidden_vcore_office:
#     entities:
#       - input_boolean.

#   options_vcore_office:
#     entities:
#       - input_boolean.

#   script_vcore_office:
#     entities:
#       - script.
