##########################################
########## COMPONENTS ####################
##########################################
switch:
  - platform: mqtt
    name: ambivision
    command_topic: "device/eventghost/led_standby"

binary_sensor:
  - platform: mqtt
    name: "PS3"
    state_topic: "device/ps3/power"
    device_class: connectivity
    payload_on: "1"
    payload_off: "0"

#-----------------------------------------------------#

automation:
##########################################
########## NOTIFICATIONS #################
##########################################

##########################################
########## AUTOMATIONS ###################
##########################################

  #********** Entertainment Center On/Off ***************************************#
  - alias: entertainment_center_turn_on_every_15m
    trigger:
      - platform: state
        entity_id: input_boolean.var_residents_home
        to: 'on'
      - platform: time
        minutes: 15
        seconds: 00
    condition:
      - condition: state
        entity_id: input_boolean.var_residents_home
        state: 'on'
      - condition: state
        entity_id: switch.sonoff_entertainment_center
        state: 'off'
      # Time - After 12:00pm, Before 9:00pm
      - condition: template
        value_template: >
          {% if states.sensor.dark_sky_daily_high_apparent_temperature.state | float > states.input_text.var_indoor_temp_ok.state | float %}
            {% set on_hour = 18 %}
          {% else %}
            {% set on_hour = 12 %}
          {% endif %}
          {% if now().hour >= on_hour and now().hour < 21 %}
            true
          {% else %}
            false
          {% endif %}
      - condition: state
        entity_id: input_boolean.override_turn_off_tv
        state: 'off'
    action:
      - service: switch.turn_on
        entity_id: switch.sonoff_entertainment_center


  - alias: entertainment_center_turn_on
    trigger:
      - platform: state
        entity_id: input_boolean.var_ps3_on
        to: 'on'
      - platform: state
        entity_id: input_boolean.var_steam_on
        to: 'on'
      - platform: state
        entity_id: input_boolean.var_dan_home
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.var_residents_home
        state: 'on'
      - condition: state
        entity_id: switch.sonoff_entertainment_center
        state: 'off'
      - condition: state
        entity_id: input_boolean.override_turn_off_tv
        state: 'off'
    action:
      - service: switch.turn_on
        entity_id: switch.sonoff_entertainment_center


  - alias: entertainment_center_turn_on_chromecast_playing
    trigger:
      - platform: state
        entity_id: sensor.vtv_chromecast_playing_app
    condition:
      - condition: state
        entity_id: input_boolean.var_residents_home
        state: 'on'
      - condition: state
        entity_id: input_boolean.override_turn_off_tv
        state: 'off'
      - condition: state
        entity_id: switch.sonoff_entertainment_center
        state: 'off'
      - condition: template
        value_template: '{{ states.sensor.vtv_chromecast_playing_app.state | lower in states.input_select.array_chromecast_playing_apps.attributes.options | lower}}'
    action:
      - service: switch.turn_on
        entity_id: switch.sonoff_entertainment_center


  - alias: entertainment_center_turn_off_mike_not_home
    trigger:
      - platform: state
        entity_id: input_boolean.var_residents_home
        from: 'on'
        to: 'off'
      - platform: time
        minutes: '/30' #every 30 min
    condition:
      - condition: state
        entity_id: input_boolean.var_residents_home
        state: 'off'
      - condition: state
        entity_id: switch.sonoff_entertainment_center
        state: 'on'
    action:
      - service: script.entertainment_center_turn_off


  - alias: tv_turned_off_red_flash
    trigger:
      platform: state
      entity_id: switch.sonoff_entertainment_center
      to: 'off'
    action:
      - service: script.notify2
        data_template:
          flash_color: "red"
          entity_id: group.tv_lights


  - alias: tv_turned_on_green_flash
    trigger:
      platform: state
      entity_id: switch.sonoff_entertainment_center
      to: 'on'
    action:
      - service: script.notify2
        data_template:
          flash_color: "green"
          entity_id: group.tv_lights


  #********** Ambivision On/Off ***************************************#
  - alias: ambivision_turn_on
    trigger:
      - platform: state
        entity_id: switch.sonoff_entertainment_center
        from: 'off'
        to: 'on'
    action:
      - service: switch.turn_on
        entity_id: switch.ambivision

  - alias: ambivision_turn_off
    trigger:
      - platform: state
        entity_id: switch.sonoff_entertainment_center
        from: 'on'
        to: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.ambivision


  #********** PS3 ***************************************#
  - alias: ps3_turn_on
    trigger:
      - platform: state
        entity_id: binary_sensor.ps3
        to: 'on'
      - platform: state
        entity_id: binary_sensor.ps3_ping
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.var_ps3_on
        state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.var_ps3_on
      - service: script.ps3_turn_on

  - alias: ps3_turn_off
    trigger:
      - platform: state
        entity_id: binary_sensor.ps3
        to: 'off'
      - platform: state
        entity_id: binary_sensor.ps3_ping
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.var_ps3_on
        state: 'on'
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.var_ps3_on
      - service: script.chromecast_turn_on


  #********** STEAM ***************************************#
  - alias: steam_turn_on
    trigger:
      - platform: state
        entity_id: input_boolean.var_steam_on
        to: 'on'
    action:
      - service: script.steam_turn_on

  - alias: steam_turn_off
    trigger:
      - platform: state
        entity_id: input_boolean.var_steam_on
        to: 'off'
    action:
      - service: script.chromecast_turn_on

##########################################
########## OVERRIDES #####################
##########################################

#********** Alexa Override Helper ***********#
  # - alias: tv_override
  #   trigger:
  #     - platform: event
  #       event_type: call_service
  #       event_data:
  #         service_data:
  #           entity_id: input_boolean.override_tv_helper
  #   action:
  #     # - service: script.notify2
  #     #   data_template:
  #     #     telegram_message: '{{ trigger | string }}'
  #     - service: script.turn_on
  #       data_template:
  #         entity_id: >
  #           {% if "turn_off" in trigger.event | string %}
  #             script.override_turn_off_tv
  #           {% else %}
  #             script.override_turn_on_tv
  #           {% endif %}

#********** Override Input Booleans - Triggers ***********#
  - alias: tv_override_turn_on
    trigger:
      - platform: state
        entity_id: input_boolean.override_turn_on_tv
        to: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.override_turn_off_tv
      - service: switch.turn_on
        entity_id: switch.sonoff_entertainment_center

  - alias: tv_override_turn_off
    trigger:
      - platform: state
        entity_id: input_boolean.override_turn_off_tv
        to: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.override_turn_on_tv
      - service: switch.turn_off
        entity_id: switch.sonoff_entertainment_center

#-----------------------------------------------------#

##########################################
########## SCRIPTS #######################
##########################################
script:
  entertainment_center_turn_off:
    sequence:
    - condition: state
      entity_id: input_boolean.var_ps3_on
      state: 'off'
    - condition: state
      entity_id: input_boolean.var_steam_on
      state: 'off'
    - condition: template
      value_template: >-
        {% if states.media_player.vtv_chromecast.state != "playing" %}
          true
        {%else%}
          {% if states.media_player.vtv_chromecast.attributes.app_name | lower in states.input_select.array_chromecast_idle_apps | lower %}
            true
          {%else%}
            false
          {%endif%}
        {%endif%}
    - condition: state
      entity_id: binary_sensor.entertainment_center_motion_sensor
      state: 'off'
    - service: switch.turn_off
      entity_id: switch.sonoff_entertainment_center


  ps3_turn_on:
    sequence:
      - service: homeassistant.turn_on
        entity_id: input_boolean.var_ps3_on
      - service: mqtt.publish
        data:
          topic: "device/eventghost/input_game"
          payload: '1'

  steam_turn_on:
    sequence:
      - service: homeassistant.turn_on
        entity_id: input_boolean.var_steam_on
      - service: mqtt.publish
        data:
          topic: "device/eventghost/input_vcr"
          payload: '1'

  chromecast_turn_on:
    sequence:
      - service: homeassistant.turn_off
        entity_id: input_boolean.var_ps3_on
      - service: homeassistant.turn_off
        entity_id: input_boolean.var_steam_on
      - service: mqtt.publish
        data:
          topic: "device/eventghost/input_cbl"
          payload: '1'


#********** Override - Turn ON  ***********#
  override_turn_on_tv:
    sequence:
      # If Override already 'on'; turn off
      - service_template: >
          {% if states.input_boolean.override_turn_on_tv.state == 'on' %}
            input_boolean.turn_off
          {% else %}
            script.do_nothing
          {% endif %}
        entity_id: input_boolean.override_turn_on_tv

      # Turn On - Override Input Boolean
      - service: input_boolean.turn_on
        entity_id: input_boolean.override_turn_on_tv

#********** Override - Turn OFF  ***********#
  override_turn_off_tv:
    sequence:
      # If Override already 'on'; turn off
      - service_template: >
          {% if states.input_boolean.override_turn_off_tv.state == 'on' %}
            input_boolean.turn_off
          {% else %}
            script.do_nothing
          {% endif %}
        entity_id: input_boolean.override_turn_off_tv

      # Turn On - Override Input Boolean
      - service: input_boolean.turn_on
        entity_id: input_boolean.override_turn_off_tv

#-----------------------------------------------------#

input_boolean:
##########################################
########## BACKEND #######################
##########################################
  var_ps3_on:
    initial: off

  var_steam_on:
    initial: off

##########################################
########## OPTIONS #######################
##########################################

##########################################
########## CONFIG ########################
##########################################

##########################################
########## OVERRIDES #####################
##########################################
  override_tv_helper:
  override_turn_on_tv:
    initial: off
  override_turn_off_tv:
    initial: off

#-----------------------------------------------------#

homeassistant:
  customize:
##########################################
########## EMULATED HUE ##################
##########################################
    input_boolean.override_tv_helper:
      emulated_hue: true
      emulated_hue_name: "TV"

    group.sonoff_entertainment_center:
      emulated_hue: true
      emulated_hue_name: "Entertainment Center"

    input_boolean.var_steam_on:
      emulated_hue: true
      emulated_hue_name: "Steam"

    input_boolean.var_ps3_on:
      emulated_hue: true
      emulated_hue_name: "PS3"

    script.ps3_turn_on:
      emulated_hue: true
      emulated_hue_name: "Playstation"

    script.chromecast_turn_on:
      emulated_hue: true
      emulated_hue_name: "Chromecast"

#-----------------------------------------------------#

group:
##########################################
############### GROUPS ###################
##########################################
  sonoff_entertainment_center: # used for multiple Alexa commands (ie. 'Entertainment Center' OR 'TV')
    entities:
      - input_boolean.override_tv_helper

##########################################
############### AUTO-GROUPS ##############
##########################################
  automation_entertainment_center:
    entities:
      - automation.entertainment_center_turn_on_every_15m
      - automation.entertainment_center_turn_on
      - automation.entertainment_center_turn_on_chromecast_playing
      - automation.entertainment_center_turn_off_mike_not_home
      - automation.tv_turned_off_red_flash
      - automation.tv_turned_on_green_flash
      - automation.ambivision_turn_on
      - automation.ambivision_turn_off
      - automation.ps3_turn_on
      - automation.ps3_turn_off
      - automation.steam_turn_on
      - automation.steam_turn_off
      - automation.tv_override
      - automation.tv_override_turn_on
      - automation.tv_override_turn_off

  backend_entertainment_center:
    entities:
      - input_boolean.override_tv_helper
      - input_boolean.override_turn_on_tv
      - input_boolean.override_turn_off_tv
      - input_boolean.var_ps3_on
      - input_boolean.var_steam_on

#   hidden_entertainment_center:
#     entities:
#       - input_boolean.

#   options_entertainment_center:
#     entities:
#       - input_boolean.

  script_entertainment_center:
    entities:
      - script.entertainment_center_turn_off
      - script.ps3_turn_on
      - script.steam_turn_on
      - script.chromecast_turn_on
      - script.override_turn_on_tv
      - script.override_turn_off_tv

  sensor_entertainment_center:
    entities:
      - switch.ambivision
      - binary_sensor.ps3
