##########################################
########## COMPONENTS ####################
##########################################
sensor:
  - platform: template
    sensors:
      vtv_chromecast_playing_app:
        friendly_name: "vTV Chromecast: Playing App"
        value_template: '{% if states.media_player.vtv_chromecast.attributes.app_name %}{{ states.media_player.vtv_chromecast.attributes.app_name | lower }}{% else %}off{% endif %}'

media_player:
  - platform: cast
    host: 192.168.1.98

  - platform: cast
    host: 192.168.1.99

  # - platform: plex

  # - platform: spotify
  #   client_id: !secret spotify_client_id
  #   client_secret: !secret spotify_client_secret

#-----------------------------------------------------#

automation:
##########################################
########## NOTIFICATIONS #################
##########################################

##########################################
########## AUTOMATIONS ###################
##########################################

  #********** Screen Saver ***************************************#
  - alias: vtv_chromecast_screensaver_mark_as_ready
    trigger:
      - platform: state
        entity_id: media_player.vtv_chromecast
        to: 'off'
        for:
          minutes: 5
      - platform: state
        entity_id: input_boolean.var_ps3_on
        to: 'off'
        for:
          minutes: 5
      - platform: state
        entity_id: input_boolean.var_steam_on
        to: 'off'
        for:
          minutes: 5
      - platform: state
        entity_id: switch.sonoff_entertainment_center
        to: 'on'
        for:
          minutes: 15
    condition:
      - condition: state
        entity_id: media_player.vtv_chromecast
        state: 'off'
      - condition: state
        entity_id: input_boolean.var_ps3_on
        state: 'off'
      - condition: state
        entity_id: input_boolean.var_steam_on
        state: 'off'
      - condition: state
        entity_id: switch.sonoff_entertainment_center
        state: 'on'
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.var_vtv_chromecast_screensaver_ready


  - alias: vtv_chromecast_screensaver_mark_as_not_ready
    trigger:
      - platform: state
        entity_id: media_player.vtv_chromecast
        from: 'off'
      - platform: state
        entity_id: input_boolean.var_ps3_on
        to: 'off'
      - platform: state
        entity_id: input_boolean.var_steam_on
        to: 'off'
      - platform: homeassistant
        event: start
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.var_vtv_chromecast_screensaver_ready


  - alias: vtv_chromecast_play_screensaver
    trigger:
      - platform: state
        entity_id: input_boolean.var_vtv_chromecast_screensaver_ready
        to: 'on'
      - platform: state
        entity_id: sensor.now_hour
    condition:
      - condition: state
        entity_id: input_boolean.var_residents_home
        state: 'on'
      - condition: state
        entity_id: switch.sonoff_entertainment_center
        state: 'on'
      - condition: state
        entity_id: input_boolean.var_ps3_on
        state: 'off'
      - condition: state
        entity_id: input_boolean.var_steam_on
        state: 'off'
      - condition: state
        entity_id: input_boolean.option_chromecast_screensaver
        state: 'on'
      - condition: state
        entity_id: input_boolean.var_vtv_chromecast_screensaver_ready
        state: 'on'
    action:
      - service: script.set_entertainment_center_tv_volume
        data:
          volume_level: 2
      - service: script.turn_on
        data_template:
          entity_id: >
            {% set hour = states.sensor.time.state[:2] | int %}

            {# 12AM TO 5AM #}
            {% if hour | int < 5 %}
              script.media_scene_fireplace

            {# 5AM TO 5PM #}
            {% elif hour | int < 17 %}
              script.media_scene_space

            {# 5PM TO 7PM #}
            {% elif hour | int < 19 %}
              script.media_scene_magenta_blue_orbs_long

            {# 7PM TO 9PM #}
            {% elif hour | int < 21 %}
              script.media_scene_lcars

            {# 7PM TO 9PM #}
            {% elif hour | int < 23 %}
              script.media_scene_fireplace

            {# 11PM TO 12AM #}
            {% elif hour | int >= 23 %}
              script.media_scene_fireplace
            {% endif %}


  #********** Default Media Player ***************************************#
  - alias: vtv_chromecast_idle_to_off
    trigger:
      - platform: state
        entity_id: media_player.vtv_chromecast
        from: 'playing'
        to: 'idle'
        for:
          seconds: 10
    condition:
      - condition: template
        value_template: '{% if states.media_player.vtv_chromecast.attributes.app_name | lower in states.input_select.array_chromecast_idle_apps | lower %}true{%else%}false{%endif%}'
    action:
      - service: media_player.turn_off
        entity_id: media_player.vtv_chromecast


  #********** Source Change ***************************************#
  - alias: vtv_chromecast_pause_video_on_source_change
    trigger:
      - platform: state
        entity_id: input_boolean.var_ps3_on
        to: 'on'
      - platform: state
        entity_id: input_boolean.var_steam_on
        to: 'on'
    condition:
      - condition: state
        entity_id: media_player.vtv_chromecast
        state: 'playing'
      - condition: or
        conditions:
        - condition: state
          entity_id: input_boolean.var_ps3_on
          state: 'on'
        - condition: state
          entity_id: input_boolean.var_steam_on
          state: 'on'
    action:
      - service: media_player.media_pause
        entity_id: media_player.vtv_chromecast

  - alias: vtv_chromecast_resume_video_on_source_change
    trigger:
      - platform: state
        entity_id: input_boolean.var_ps3_on
        from: 'on'
        to: 'off'
      - platform: state
        entity_id: input_boolean.var_steam_on
        from: 'on'
        to: 'off'
    condition:
      - condition: state
        entity_id: media_player.vtv_chromecast
        state: 'paused'
      - condition: state
        entity_id: input_boolean.var_ps3_on
        state: 'off'
      - condition: state
        entity_id: input_boolean.var_steam_on
        state: 'off'
    action:
      - service: media_player.media_play
        entity_id: media_player.vtv_chromecast


  #********** TTS Interupt ***************************************#
  - alias: vtv_chromecast_tts_interupt_pause_video
    trigger:
      - platform: state
        entity_id: input_boolean.var_tts_interupt
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: media_player.vtv_chromecast
        state: 'playing'
    action:
      - service: media_player.media_pause
        entity_id: media_player.vtv_chromecast

  - alias: vtv_chromecast_tts_interupt_resume_video
    trigger:
      - platform: state
        entity_id: input_boolean.var_tts_interupt
        from: 'on'
        to: 'off'
    condition:
      - condition: state
        entity_id: media_player.vtv_chromecast
        state: 'paused'
    action:
      - service: media_player.media_play
        entity_id: media_player.vtv_chromecast

#-----------------------------------------------------#

script:
##########################################
########## SCRIPTS #######################
##########################################
  test_spotify:
    sequence:
      - service: media_player.select_source
        data:
          entity_id: media_player.spotify
          source: 'vTV Chromecast'
      - service: media_player.play_media
        data:
          entity_id: media_player.spotify
          media_content_type: playlist
          media_content_id: spotify:user:techv76:playlist:6olCTXXKum4I5AifEaXNnT


##########################################
########## USER THEMES ###################
##########################################
  media_scene_battlestar_galactica_intro:
    alias: "battlestar_galactica_intro"
    sequence:
      - service: media_player.play_media
        data:
          entity_id: media_player.vtv_chromecast
          media_content_type: video/mp4
          media_content_id: http://192.168.1.3:8123/local/video/user_theme_songs/battlestar_galactica_intro.mp4

  media_scene_bushes_of_love:
    alias: "bushes_of_love"
    sequence:
      - service: media_player.play_media
        data:
          entity_id: media_player.vtv_chromecast
          media_content_type: video/mp4
          media_content_id: http://192.168.1.3:8123/local/video/user_theme_songs/bushes_of_love.mp4

  media_scene_whats_up_bitches:
    alias: "whats_up_bitches"
    sequence:
      - service: media_player.play_media
        data:
          entity_id: media_player.vtv_chromecast
          media_content_type: video/mp4
          media_content_id: http://192.168.1.3:8123/local/video/user_theme_songs/whats_up_bitches.mp4

##########################################
########## SCREEN SAVERS #################
##########################################
  media_scene_magenta_blue_orbs_long:
    alias: "magenta_blue_orbs_long"
    sequence:
      - service: media_player.play_media
        data:
          entity_id: media_player.vtv_chromecast
          media_content_type: video/mp4
          media_content_id: http://192.168.1.3:8123/local/video/screensavers/magenta_blue_orbs_long.mp4

  media_scene_space:
    alias: "space"
    sequence:
      - service: media_player.play_media
        data:
          entity_id: media_player.vtv_chromecast
          media_content_type: video/mp4
          media_content_id: http://192.168.1.3:8123/local/video/screensavers/space.mp4

  media_scene_fireplace:
    alias: "fireplace"
    sequence:
      - service: media_player.play_media
        data:
          entity_id: media_player.vtv_chromecast
          media_content_type: video/mp4
          media_content_id: http://192.168.1.3:8123/local/video/screensavers/fireplace.mp4

  media_scene_lcars:
    alias: "LCARS"
    sequence:
      - service: media_player.play_media
        data:
          entity_id: media_player.vtv_chromecast
          media_content_type: video/mp4
          media_content_id: http://192.168.1.3:8123/local/video/screensavers/lcars_720p.mp4

#-----------------------------------------------------#

input_boolean:
##########################################
########## OPTIONS #######################
##########################################
  option_chromecast_screensaver:
    name: "Chromecast Screensaver"
    initial: on

##########################################
########## BACKEND #######################
##########################################
  var_tts_interupt: #Activated when TTS is playing, turns off when TTS is idle
    initial: off
  var_vtv_chromecast_screensaver_ready:

input_select:
  array_chromecast_playing_apps:
    options:
      - "Netflix"
      - "YouTube"
      - "Spotify"
      - "Plex"
      - "Chrome Mirroring"

  array_chromecast_idle_apps:
    options:
      - "Backdrop"
      - "Default Media Receiver"
      - "Default Media Player"

##########################################
########## CONFIG ########################
##########################################

#-----------------------------------------------------#

# homeassistant:
#   customize:
##########################################
########## EMULATED HUE ##################
##########################################
    # input_boolean.template:
    #   emulated_hue: true
    #   emulated_hue_name: "Template Name"

#-----------------------------------------------------#

group:
##########################################
############### GROUPS ###################
##########################################
  tools_test_media_center:
    name: "Test - Media Center"
    control: hidden
    entities:
      - script.test_spotify

##########################################
############### AUTO-GROUPS ##############
##########################################
  automation_media_player:
    entities:
      - automation.vtv_chromecast_screensaver_mark_as_ready
      - automation.vtv_chromecast_screensaver_mark_as_not_ready
      - automation.vtv_chromecast_play_screensaver
      - automation.vtv_chromecast_idle_to_off
      - automation.vtv_chromecast_pause_video_on_source_change
      - automation.vtv_chromecast_resume_video_on_source_change
      - automation.tts_started_pause_video
      - automation.tts_complete_resume_video
      - automation.vtv_chromecast_tts_interupt_pause_video
      - automation.vtv_chromecast_tts_interupt_resume_video

  backend_media_player:
    entities:
      - input_boolean.var_vtv_chromecast_screensaver_ready
      - input_boolean.var_tts_interupt

  hidden_media_player:
    entities:
      - input_select.array_chromecast_playing_apps
      - input_select.array_chromecast_idle_apps

  options_media_player:
    name: "Media Player"
    entities:
      - input_boolean.option_chromecast_screensaver

  script_media_player:
    entities:
      - script.media_scene_battlestar_galactica_intro
      - script.media_scene_bushes_of_love
      - script.media_scene_whats_up_bitches
      - script.media_scene_magenta_blue_orbs_long
      - script.media_scene_space
      - script.media_scene_fireplace
      - script.media_scene_lcars

  sensor_media_player:
    entities:
      - sensor.vtv_chromecast_playing_app
