##########################################
########## COMPONENTS ####################
##########################################
# sensor:

#-----------------------------------------------------#

# automation:
##########################################
########## NOTIFICATIONS #################
##########################################

##########################################
########## AUTOMATIONS ###################
##########################################

#-----------------------------------------------------#

##########################################
########## SCRIPTS #######################
##########################################
script:
  call_last_known_scene: # [rooms, transition]
    sequence:
      # Living Room
      - service_template: >
          {% if not rooms or "all" in rooms or "livingroom" in rooms %}
            script.scene2_{{ states.input_text.var_lks_livingroom.state }}_livingroom
          {% else %}
            script.scene2_do_nothing
          {% endif %}
        data_template:
          transition: '{% if transition %} {{ transition }} {%else%} 1 {% endif %}'

      # Office
      - service_template: >
          {% if not rooms or "all" in rooms or "office" in rooms %}
            script.scene2_{{ states.input_text.var_lks_office.state }}_office
          {% else %}
            script.scene2_do_nothing
          {% endif %}
        data_template:
          transition: '{% if transition %} {{ transition }} {%else%} 1 {% endif %}'

      # Kitchen
      - service_template: >
          {% if not rooms or "all" in rooms or "kitchen" in rooms %}
            script.scene2_{{ states.input_text.var_lks_kitchen.state }}_kitchen
          {% else %}
            script.scene2_do_nothing
          {% endif %}
        data_template:
          transition: '{% if transition %} {{ transition }} {%else%} 1 {% endif %}'

      # Re-send Kitchen LED State
      - service: mqtt.publish
        data_template:
          topic: "device/kitchen/led1/power"
          payload: >
            {% if states.light.kitchen_led_strip.state == 'on' %}
              1
            {% else %}
              0
            {% endif %}

      # Re-send Kitchen LED Brightness
      - service: mqtt.publish
        data_template:
          topic: "device/kitchen/led1/brightness"
          payload: '{{ states.light.kitchen_led_strip.attributes.brightness }}'

      # Re-send Kitchen LED Effect
      - service: mqtt.publish
        data_template:
          topic: "device/kitchen/led1/effect"
          payload: >
            {% for opt in states.input_select.office_led_effect.attributes.options -%}
              {% if states.input_select.office_led_effect.state | string == opt %}
                {{loop.index - 1}}
              {%endif%}
            {%- endfor -%}

      # Bedroom
      - service_template: >
          {% if not rooms or "all" in rooms or "bedroom" in rooms %}
            script.scene2_{{ states.input_text.var_lks_bedroom.state }}_bedroom
          {% else %}
            script.scene2_do_nothing
          {% endif %}
        data_template:
          transition: '{% if transition %} {{ transition }} {%else%} 1 {% endif %}'

#-----------------------------------------------------#


##########################################
########## BACKEND #######################
##########################################
input_text:
  var_lks_livingroom:
    initial: ""

  var_lks_office:
    initial: ""

  var_lks_kitchen:
    initial: ""

  var_lks_bedroom:
    initial: ""

##########################################
########## OPTIONS #######################
##########################################

##########################################
########## CONFIG ########################
##########################################

#-----------------------------------------------------#

homeassistant:
  customize:
##########################################
########## EMULATED HUE ##################
##########################################
    script.call_last_known_scene:
      emulated_hue: true
      emulated_hue_name: "Fix Lights"

#-----------------------------------------------------#

group:
##########################################
############### GROUPS ###################
##########################################

##########################################
############### AUTO-GROUPS ##############
##########################################
#   automation_last_known_scene:
#     entities:
#       - automation.

  backend_last_known_scene:
    entities:
      - input_text.var_lks_livingroom
      - input_text.var_lks_office
      - input_text.var_lks_kitchen
      - input_text.var_lks_bedroom

#   hidden_last_known_scene:
#     entities:
#       - input_boolean.

#   options_last_known_scene:
#     entities:
#       - input_boolean.

  script_last_known_scene:
    entities:
      - script.call_last_known_scene

#   sensor_last_known_scene:
#     entities:
#       - sensor.
