  - platform: mqtt
    name: "Kitchen Temperature"
    state_topic: "device/kitchen/temperature"
    qos: 0
    unit_of_measurement: "ºF"

  - platform: mqtt
    name: "Kitchen Humidity"
    state_topic: "device/kitchen/humidity"
    qos: 0
    unit_of_measurement: "%"

  - platform: mqtt
    name: "Tables Temperature"
    state_topic: "device/tables/temperature"
    qos: 0
    unit_of_measurement: "ºF"

  - platform: mqtt
    name: "Tables Humidity"
    state_topic: "device/tables/humidity"
    qos: 0
    unit_of_measurement: "%"

  - platform: mqtt
    name: "Entertainment Center Temperature"
    state_topic: "device/entertainment_center/temperature"
    qos: 0
    unit_of_measurement: "ºF"

  - platform: mqtt
    name: "Entertainment Center Humidity"
    state_topic: "device/entertainment_center/humidity"
    qos: 0
    unit_of_measurement: "%"

  - platform: mqtt
    name: "Bedroom Temperature"
    state_topic: "device/bedroom/temperature"
    qos: 0
    unit_of_measurement: "ºF"

  - platform: mqtt
    name: "Bedroom Humidity"
    state_topic: "device/bedroom/humidity"
    qos: 0
    unit_of_measurement: "%"
