  - platform: mqtt
    name: "Kitchen Temperature"
    state_topic: "sensor/kitchen_temperature"
    qos: 0
    unit_of_measurement: "ºF"

  - platform: mqtt
    name: "Kitchen Humidity"
    state_topic: "sensor/kitchen_humidity"
    qos: 0
    unit_of_measurement: "%"
