##########################################
########## LOGGER ########################
##########################################
- alias: Log Level
  trigger:
    platform: state
    entity_id: input_select.option_log_level
  action:
    service: logger.set_level
    data_template:
      homeassistant.components: "{{ trigger.to_state.state }}"
