
##########################################
############### SCENE CHANGE ###############
##########################################

- alias: set_var_last_known_scene
  trigger:
  - platform: event
    event_type: 'call_service'
    event_data:
      service: turn_on
      domain: scene
  action:
  - condition: template
    value_template: >
      {% if trigger.event.data.service_data.entity_id[0][6:] | replace("10m_", "") | replace("0s_", "") | replace("_", " ") | title != "" %}
        true
      {% else %}
        false
      {% endif %}
  - service: input_select.select_option
    data_template:
      entity_id: input_select.var_last_known_scene
      option: '{{ trigger.event.data.service_data.entity_id[0][6:] | replace("10m_", "") | replace("0s_", "") | replace("_", " ") | title }}'
  - condition: state
    entity_id: input_select.var_kitchen_on
    state: 'on'
  - service: input_slider.select_value
    data_template:
      entity_id: input_slider.var_kitchen_brightness
      value: '{{ states.light.kitchen_left.attributes.brightness }}'
  - service: input_slider.select_value
    data_template:
      entity_id: input_slider.var_kitchen_color_temp
      value: '{{ states.light.kitchen_left.attributes.color_temp }}'

- alias: set_var_last_known_scene2
  trigger:
  - platform: event
    event_type: 'call_service'
    event_data:
      service: turn_on
      domain: scene
  action:
  - condition: template
    value_template: >
      {% if trigger.event.data.service_data.entity_id[6:] | replace("10m_", "") | replace("0s_", "") | replace("_", " ") | title != "" %}
        true
      {% else %}
        false
      {% endif %}
  - service: input_select.select_option
    data_template:
      entity_id: input_select.var_last_known_scene
      option: '{{ trigger.event.data.service_data.entity_id[6:] | replace("10m_", "") | replace("0s_", "") | replace("_", " ") | title }}'
  - condition: state
    entity_id: input_select.var_kitchen_on
    state: 'on'
  - service: input_slider.select_value
    data_template:
      entity_id: input_slider.var_kitchen_brightness
      value: '{{ states.light.kitchen_left.attributes.brightness }}'
  - service: input_slider.select_value
    data_template:
      entity_id: input_slider.var_kitchen_color_temp
      value: '{{ states.light.kitchen_left.attributes.color_temp }}'

##########################################
############### SCENE OFF ###############
##########################################

- alias: set_var_last_known_scene_to_off
  trigger:
  - platform: state
    entity_id: group.all_lights
    state: 'off'
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.var_last_known_scene
      option: 'Off'

# - alias: set_var_last_known_scene_from_off
#   trigger:
#     - platform: state
#       entity_id: group.all_lights
#       from: 'off'
#       to: 'on'
#       for:
#         seconds: 1
#   action:
#     - condition: state
#       entity_id: input_select.var_last_known_scene
#       state: 'Off'
#     - service: script.timebased_scene
