##########################################
########## COMPONENTS ####################
##########################################
switch:
  - platform: mqtt
    name: air_conditioner
    command_topic: "device/office/ir_send"
    payload_on: "0x10AF8877"
    payload_off: "0x10AF8877"

#-----------------------------------------------------#

# automation:
##########################################
########## NOTIFICATIONS #################
##########################################

automation:
##########################################
########## OVERRIDES ###################
##########################################

#********** Alexa Override Helper ***********#
  # - alias: air_conditioner_override
  #   trigger:
  #     - platform: event
  #       event_type: call_service
  #       event_data:
  #         service_data:
  #           entity_id: input_boolean.override_air_conditioner_helper
  #   action:
  #     # - service: script.notify2
  #     #   data_template:
  #     #     telegram_message: '{{ trigger | string }}'
  #     - service: script.turn_on
  #       data_template:
  #         entity_id: >
  #           {% if "turn_off" in trigger.event | string %}
  #             script.override_turn_off_air_conditioner
  #           {% else %}
  #             script.override_turn_on_air_conditioner
  #           {% endif %}

#********** Override Input Booleans - Triggers ***********#
  - alias: air_conditioner_override_turn_on
    trigger:
      - platform: state
        entity_id: input_boolean.override_turn_on_air_conditioner
        to: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.override_turn_off_air_conditioner
      - service: switch.turn_on
        entity_id: switch.air_conditioner

  - alias: air_conditioner_override_turn_off
    trigger:
      - platform: state
        entity_id: input_boolean.override_turn_off_air_conditioner
        to: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.override_turn_on_air_conditioner
      - service: switch.turn_off
        entity_id: switch.air_conditioner

##########################################
########## AUTOMATIONS ###################
##########################################
  #******** Air Conditioner - Temp/Humidity Controlled - Turn On/Off **********************#
  - alias: air_conditioner_temperature_controlled_on
    trigger:
      - platform: state
        entity_id: input_boolean.option_indoor_temp_very_hot
        to: 'on'
      - platform: state
        entity_id: input_boolean.option_indoor_temp_hot
        to: 'on'
      - platform: state
        entity_id: input_boolean.option_indoor_humidity_high
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.option_air_conditioner_temperature_controlled
        state: 'on'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.var_air_conditioner_temperature_controlled_on

  - alias: air_conditioner_temperature_controlled_off
    trigger:
      - platform: state
        entity_id: input_boolean.option_indoor_temp_ok
        to: 'on'
      - platform: state
        entity_id: input_boolean.option_indoor_temp_cool
        to: 'on'
      - platform: state
        entity_id: input_boolean.option_indoor_temp_cold
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.option_air_conditioner_temperature_controlled
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_air_conditioner_temperature_controlled_on


  #********** Air Conditioner - Automations - On/Off ******************************#
  - alias: air_conditioner_automations_turn_on
    trigger:
      - platform: state
        entity_id: input_boolean.var_air_conditioner_temperature_controlled_on
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.override_turn_off_air_conditioner
        state: 'off'
    action:
      - service: switch.turn_on
        entity_id: switch.air_conditioner

  - alias: air_conditioner_automations_turn_off
    trigger:
      - platform: state
        entity_id: input_boolean.var_air_conditioner_temperature_controlled_on
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.var_air_conditioner_temperature_controlled_on
        state: 'off'
      - condition: state
        entity_id: input_boolean.override_turn_on_air_conditioner
        state: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.air_conditioner



  #********** Volume Adjustment - Air Conditioner On/Off **********************************#
  - alias: air_conditioner_on_devices_volume_up
    trigger:
      - platform: state
        entity_id: switch.air_conditioner
        to: 'on'
    action:
      - delay: '00:00:01'

      # All Computers - Volume up 4%
      - service: script.set_computers_volume
        data:
          volume_up: 4

      # Entertainment Center - Volume up 3 clicks
      - condition: state
        entity_id: switch.sonoff_entertainment_center
        state: 'on'
      - service: script.set_entertainment_center_tv_volume
        data:
          volume_up: 3

      # TTS
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.vlc
          volume_level: >
            {% if states.media_player.vlc.attributes.volume_level | float <= 0.90 %}
              {{ states.media_player.vlc.attributes.volume_level | float + 0.10 }}
            {% else %}
              {{ states.media_player.vlc.attributes.volume_level | float }}
            {% endif %}


  - alias: air_conditioner_off_devices_volume_down
    trigger:
      - platform: state
        entity_id: switch.air_conditioner
        to: 'off'
    action:
      - delay: '00:00:01'

      # All Computers - Volume down 4%
      - service: script.set_computers_volume
        data:
          volume_down: 4

      # Entertainment Center - Volume down 3 clicks
      - condition: state
        entity_id: switch.sonoff_entertainment_center
        state: 'on'
      - service: script.set_entertainment_center_tv_volume
        data:
          volume_down: 3

      # TTS
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.vlc
          volume_level: '{{ states.media_player.vlc.attributes.volume_level | float - 0.10 }}'

  #********** TTS Interupt ***************************************#
  - alias: tts_interupt_turn_off_air_conditioner
    trigger:
      - platform: state
        entity_id: input_boolean.var_tts_interupt
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: switch.air_conditioner
        state: 'on'
    action:
      - service: switch.turn_off
        entity_id: switch.air_conditioner
      - wait_template: "{{ states.input_boolean.var_tts_interupt.state == 'off' }}"
        timeout: 00:02:00
      - service: switch.turn_on
        entity_id: switch.air_conditioner

  #********** Turn off Air Conditioner if on over 2 hours ***********#
  - alias: air_conditioner_turn_off_over_2h
    trigger:
      - platform: state
        entity_id: input_select.var_air_conditioner_temperature_controlled_on
        to: 'on'
        for:
          hours: 2
    action:
      - service: input_boolean.turn_off
        entity_id: input_select.var_air_conditioner_temperature_controlled_on

#-----------------------------------------------------#

##########################################
########## SCRIPTS #######################
##########################################
script:
  fix_air_conditioner_sync:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: "device/office/ir_send"
          payload: "0x10AF8877"

#********** Override - Turn ON  ***********#
  override_turn_on_air_conditioner:
    sequence:
      # If Override already 'on'; turn off
      - service_template: >
          {% if states.input_boolean.override_turn_on_air_conditioner.state == 'on' %}
            input_boolean.turn_off
          {% else %}
            script.do_nothing
          {% endif %}
        entity_id: input_boolean.override_turn_on_air_conditioner

      # Turn On - Override Input Boolean
      - service: input_boolean.turn_on
        entity_id: input_boolean.override_turn_on_air_conditioner

#********** Override - Turn OFF  ***********#
  override_turn_off_air_conditioner:
    sequence:
      # If Override already 'on'; turn off
      - service_template: >
          {% if states.input_boolean.override_turn_off_air_conditioner.state == 'on' %}
            input_boolean.turn_off
          {% else %}
            script.do_nothing
          {% endif %}
        entity_id: input_boolean.override_turn_off_air_conditioner

      # Turn On - Override Input Boolean
      - service: input_boolean.turn_on
        entity_id: input_boolean.override_turn_off_air_conditioner

#-----------------------------------------------------#

input_boolean:
##########################################
########## BACKEND #######################
##########################################
  var_air_conditioner_temperature_controlled_on:

##########################################
########## OVERRIDES #####################
##########################################
  override_air_conditioner_helper:
  override_turn_on_air_conditioner:
  override_turn_off_air_conditioner:

##########################################
########## OPTIONS #######################
##########################################
  option_air_conditioner_temperature_controlled:
    name: "Temperature controlled Air Conditioner"
    initial: on

##########################################
########## CONFIG ########################
##########################################

#-----------------------------------------------------#

homeassistant:
  customize:
##########################################
########## EMULATED HUE ##################
##########################################
    input_boolean.override_air_conditioner_helper:
      emulated_hue: true
      emulated_hue_name: "Air Conditioner"
    script.fix_air_conditioner_sync:
      emulated_hue: true
      emulated_hue_name: "Fix Air Conditioner"

#-----------------------------------------------------#

group:
##########################################
############### GROUPS ###################
##########################################

##########################################
############### AUTO-GROUPS ##############
##########################################
  automation_air_conditioner:
    entities:
      - automation.air_conditioner_temperature_controlled_on
      - automation.air_conditioner_temperature_controlled_off
      - automation.air_conditioner_automations_turn_on
      - automation.air_conditioner_automations_turn_off
      - automation.air_conditioner_override
      - automation.air_conditioner_override_turn_on
      - automation.air_conditioner_override_turn_off
      - automation.air_conditioner_on_devices_volume_up
      - automation.air_conditioner_off_devices_volume_down
      - automation.tts_interupt_turn_off_air_conditioner
      - automation.air_conditioner_turn_off_over_2h

  backend_air_conditioner:
    entities:
      - input_boolean.var_air_conditioner_temperature_controlled_on
      - input_boolean.override_air_conditioner_helper
      - input_boolean.override_turn_on_air_conditioner
      - input_boolean.override_turn_off_air_conditioner

#   hidden_air_conditioner:
#     entities:
#       - input_boolean.

  options_air_conditioner:
    name: "Air Conditioner"
    entities:
      - input_boolean.option_air_conditioner_temperature_controlled

  script_air_conditioner:
    entities:
      - script.fix_air_conditioner_sync
      - script.override_turn_on_air_conditioner
      - script.override_turn_off_air_conditioner

  sensor_air_conditioner:
    entities:
      - switch.air_conditioner
