##########################################
########## COMPONENTS ####################
##########################################
# sensor:

#-----------------------------------------------------#

automation:
##########################################
########## NOTIFICATIONS #################
##########################################

##########################################
########## AUTOMATIONS ###################
##########################################

  #********** Kitchen Motion ***************************************#
  - alias: var_kitchen_motion_on
    trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion_sensor
      from: 'off'
      to: 'on'
    action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.var_kitchen_motion_on


  #********** Enterainment Center Motion ***************************************#
  - alias: var_entertainment_center_motion_on
    trigger:
    - platform: state
      entity_id: binary_sensor.entertainment_center_motion_sensor
      from: 'off'
      to: 'on'
    action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.var_entertainment_center_motion_on

  - alias: var_entertainment_center_motion_off
    trigger:
    - platform: state
      entity_id: binary_sensor.entertainment_center_motion_sensor
      from: 'on'
      to: 'off'
      for:
        minutes: 5
    action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.var_entertainment_center_motion_on


#-----------------------------------------------------#

# script:
##########################################
########## SCRIPTS #######################
##########################################

#-----------------------------------------------------#

input_boolean:
##########################################
########## BACKEND #######################
##########################################
  var_kitchen_motion_on:
  var_entertainment_center_motion_on:

##########################################
########## OPTIONS #######################
##########################################

##########################################
########## CONFIG ########################
##########################################

#-----------------------------------------------------#

# homeassistant:
#   customize:
##########################################
########## EMULATED HUE ##################
##########################################
    # input_boolean.template:
    #   emulated_hue: true
    #   emulated_hue_name: "Template Name"

#-----------------------------------------------------#

group:
##########################################
############### GROUPS ###################
##########################################

##########################################
############### AUTO-GROUPS ##############
##########################################
  automation_motion_detection:
    entities:
      - automation.var_kitchen_motion_on
      - automation.var_entertainment_center_motion_on
      - automation.var_entertainment_center_motion_off

  backend_motion_detection:
    entities:
      - input_boolean.var_kitchen_motion_on
      - input_boolean.var_entertainment_center_motion_on

#   config_motion_detection:
#     entities:
#       - input_boolean.

  hidden_motion_detection:
    entities:
      - binary_sensor.kitchen_motion_sensor
      - binary_sensor.sink_motion_sensor
      - binary_sensor.entertainment_center_motion_sensor
      - binary_sensor.bedroom_motion_sensor
      - binary_sensor.office_motion_sensor

#   options_motion_detection:
#     entities:
#       - input_boolean.

#   script_motion_detection:
#     entities:
#       - script.
