homeassistant:
  customize:
    script.target_temperature_offset_down:
      emulated_hue: true
      emulated_hue_name: "Temperature Down"
    script.target_temperature_offset_up:
      emulated_hue: true
      emulated_hue_name: "Temperature Up"
# switch:
# lights:
# binary_sensor:
sensor:
  - platform: template
    sensors:
      indoor_temp_hot_level:
        value_template: '{{ states.input_slider.var_indoor_temp_hot.state | float + states.input_slider.option_target_temperature_offset.state | float + states.input_slider.var_indoor_temp_time_of_day.state | float + states.input_slider.var_indoor_temp_mike_at_work.state | float }}'
      indoor_temp_very_warm_level:
        value_template: '{{ states.input_slider.var_indoor_temp_very_warm.state | float + states.input_slider.option_target_temperature_offset.state | float + states.input_slider.var_indoor_temp_time_of_day.state | float + states.input_slider.var_indoor_temp_mike_at_work.state | float }}'
      indoor_temp_warm_level:
        value_template: '{{ states.input_slider.var_indoor_temp_warm.state | float + states.input_slider.option_target_temperature_offset.state | float + states.input_slider.var_indoor_temp_time_of_day.state | float + states.input_slider.var_indoor_temp_mike_at_work.state | float }}'
      indoor_temp_ok_level:
        value_template: '{{ states.input_slider.var_indoor_temp_ok.state | float + states.input_slider.option_target_temperature_offset.state | float + states.input_slider.var_indoor_temp_time_of_day.state | float + states.input_slider.var_indoor_temp_mike_at_work.state | float }}'
      indoor_temp_cool_level:
        value_template: '{{ states.input_slider.var_indoor_temp_cool.state | float + states.input_slider.option_target_temperature_offset.state | float + states.input_slider.var_indoor_temp_time_of_day.state | float + states.input_slider.var_indoor_temp_mike_at_work.state | float }}'
      indoor_temp_time_of_day_offset:
        value_template: '{{ states.input_slider.var_indoor_temp_time_of_day.state | float  }}'
      indoor_temp_mike_at_work_offset:
        value_template: '{{ states.input_slider.var_indoor_temp_mike_at_work.state | float  }}'


automation:
##########################################
########## SET INDOOR TEMP RANGE #########
##########################################
  - alias: set_indoor_temp_hot
    trigger:
      - platform: template
        value_template: '{% if  states.sensor.indoor_temperature.state  %}{% if states.sensor.indoor_temperature.state | float  > states.sensor.indoor_temp_hot_level.state | float %}true{%endif%}{%endif%}'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.var_indoor_temp_hot

  - alias: set_indoor_temp_very_warm
    trigger:
      - platform: template
        value_template: '{% if  states.sensor.indoor_temperature.state  %}{% if states.sensor.indoor_temperature.state | float > states.sensor.indoor_temp_very_warm_level.state | float and states.sensor.indoor_temperature.state | float < states.sensor.indoor_temp_hot_level.state | float %}true{%endif%}{%endif%}'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.var_indoor_temp_very_warm

  - alias: set_indoor_temp_warm
    trigger:
      - platform: template
        value_template: '{% if  states.sensor.indoor_temperature.state  %}{% if states.sensor.indoor_temperature.state | float > states.sensor.indoor_temp_warm_level.state | float and states.sensor.indoor_temperature.state | float < states.sensor.indoor_temp_very_warm_level.state | float %}true{%endif%}{%endif%}'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.var_indoor_temp_warm

  - alias: set_indoor_temp_ok
    trigger:
      - platform: template
        value_template: '{% if  states.sensor.indoor_temperature.state  %}{% if states.sensor.indoor_temperature.state | float > states.sensor.indoor_temp_ok_level.state | float and states.sensor.indoor_temperature.state | float  < states.sensor.indoor_temp_warm_level.state | float %}true{%endif%}{%endif%}'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.var_indoor_temp_ok

  - alias: set_indoor_temp_cool
    trigger:
      - platform: template
        value_template: '{% if  states.sensor.indoor_temperature.state  %}{% if states.sensor.indoor_temperature.state | float > states.sensor.indoor_temp_cool_level.state | float and states.sensor.indoor_temperature.state | float < states.sensor.indoor_temp_ok_level.state | float %}true{%endif%}{%endif%}'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.var_indoor_temp_cool

  - alias: set_indoor_temp_cold
    trigger:
      - platform: template
        value_template: '{% if  states.sensor.indoor_temperature.state  %}{% if states.sensor.indoor_temperature.state | float < states.sensor.indoor_temp_cool_level.state | float %}true{%endif%}{%endif%}'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.var_indoor_temp_cold

##########################################
########## SET INDOOR HUMIDITY RANGE #####
##########################################
  - alias: set_indoor_humidity_high
    trigger:
      - platform: template
        value_template: '{% if  states.sensor.indoor_humidity.state  %}{% if states.sensor.indoor_humidity.state | float  > 65.0 %}true{%endif%}{%endif%}'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.var_indoor_humidity_high

      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_humidity_ok
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_humidity_low

  - alias: set_indoor_humidity_ok
    trigger:
      - platform: template
        value_template: '{% if  states.sensor.indoor_humidity.state  %}{% if states.sensor.indoor_humidity.state | float > 25.0 | float and states.sensor.indoor_humidity.state | float < 65.0 %}true{%endif%}{%endif%}'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.var_indoor_humidity_ok

      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_humidity_high
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_humidity_low

  - alias: set_indoor_humidity_low
    trigger:
      - platform: template
        value_template: '{% if  states.sensor.indoor_humidity.state  %}{% if states.sensor.indoor_humidity.state | float < 25.0 %}true{%endif%}{%endif%}'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.var_indoor_humidity_low

      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_humidity_ok
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_humidity_high

##########################################
########## SET OTHER INPUT BOOLEANS ######
##########################################
  - alias: indoor_temp_hot
    trigger:
      - platform: state
        entity_id: input_boolean.var_indoor_temp_hot
        to: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_very_warm
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_warm
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_ok
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_cool
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_cold

  - alias: indoor_temp_very_warm
    trigger:
      - platform: state
        entity_id: input_boolean.var_indoor_temp_very_warm
        to: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_hot
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_warm
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_ok
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_cool
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_cold

  - alias: indoor_temp_warm
    trigger:
      - platform: state
        entity_id: input_boolean.var_indoor_temp_warm
        to: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_hot
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_very_warm
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_ok
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_cool
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_cold

  - alias: indoor_temp_ok
    trigger:
      - platform: state
        entity_id: input_boolean.var_indoor_temp_ok
        to: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_hot
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_very_warm
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_warm
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_cool
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_cold

  - alias: indoor_temp_cool
    trigger:
      - platform: state
        entity_id: input_boolean.var_indoor_temp_cool
        to: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_hot
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_very_warm
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_warm
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_ok
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_cold


  - alias: indoor_temp_cold
    trigger:
      - platform: state
        entity_id: input_boolean.var_indoor_temp_cold
        to: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_hot
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_very_warm
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_warm
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_ok
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_cool

  - alias: reset_option_target_temperature_offset
    trigger:
      - platform: state
        entity_id: input_slider.option_target_temperature_offset
      - platform: homeassistant
        event: start
    condition:
      - condition: state
        entity_id: input_slider.option_target_temperature_offset
        state: '-5.0'
    action:
      - service: input_slider.select_value
        data:
          entity_id: input_slider.option_target_temperature_offset
          value: 0.0

  - alias: reset_var_indoor_temp_time_of_day
    trigger:
      - platform: state
        entity_id: input_slider.var_indoor_temp_time_of_day
      - platform: homeassistant
        event: start
    condition:
      - condition: state
        entity_id: input_slider.var_indoor_temp_time_of_day
        state: '-3.0'
    action:
      - service: input_slider.select_value
        data:
          entity_id: input_slider.var_indoor_temp_time_of_day
          value: 0.0

  - alias: reset_var_indoor_temp_mike_at_work
    trigger:
      - platform: state
        entity_id: input_slider.var_indoor_temp_mike_at_work
      - platform: homeassistant
        event: start
    condition:
      - condition: state
        entity_id: input_slider.var_indoor_temp_mike_at_work
        state: '-1.0'
    action:
      - service: input_slider.select_value
        data:
          entity_id: input_slider.var_indoor_temp_mike_at_work
          value: 0.0

##########################################
########## TIMEBASDED TEMPERATURE ########
##########################################
  # 12am to 10am
  - alias: indoor_temp_time_12am
    trigger:
      - platform: time
        minutes: 05
        seconds: 00
    condition:
      - condition: time
        after: '00:00:00'
        before: '10:00:00'
    action:
      - service: input_slider.select_value
        data:
          entity_id: input_slider.var_indoor_temp_time_of_day
          value: 0

  # 10am to 4pm
  - alias: indoor_temp_time_10am
    trigger:
      - platform: time
        minutes: 05
        seconds: 00
    condition:
      - condition: time
        after: '10:00:00'
        before: '16:00:00'
    action:
      - service: input_slider.select_value
        data:
          entity_id: input_slider.var_indoor_temp_time_of_day
          value: 1

  # 4pm to 7pm
  - alias: indoor_temp_time_4pm
    trigger:
      - platform: time
        minutes: 05
        seconds: 00
    condition:
      - condition: time
        after: '16:00:00'
        before: '19:00:00'
    action:
      - service: input_slider.select_value
        data:
          entity_id: input_slider.var_indoor_temp_time_of_day
          value: 0

  # 7pm to 9pm
  - alias: indoor_temp_time_7pm
    trigger:
      - platform: time
        minutes: 05
        seconds: 00
    condition:
      - condition: time
        after: '19:00:00'
        before: '21:00:00'
    action:
      - service: input_slider.select_value
        data:
          entity_id: input_slider.var_indoor_temp_time_of_day
          value: -2

  # 9pm to 12am
  - alias: indoor_temp_time_9pm
    trigger:
      - platform: time
        minutes: 05
        seconds: 00
    condition:
      - condition: time
        after: '21:00:00'
        before: '23:59:59'
    action:
      - service: input_slider.select_value
        data:
          entity_id: input_slider.var_indoor_temp_time_of_day
          value: -1

##########################################
########## MIKE AT WORK TEMPERATURE ######
##########################################
  - alias: indoor_temp_mike_at_work
    trigger:
      - platform: state
        entity_id: input_boolean.var_mike_at_work
        to: 'on'
    action:
      - service: input_slider.select_value
        data:
          entity_id: input_slider.var_indoor_temp_mike_at_work
          value: 4

  - alias: indoor_temp_mike_not_at_work
    trigger:
      - platform: state
        entity_id: input_boolean.var_mike_at_work
        to: 'off'
    action:
      - service: input_slider.select_value
        data:
          entity_id: input_slider.var_indoor_temp_mike_at_work
          value: 0

##########################################
########## SCRIPTS #######################
##########################################s
script:
  target_temperature_offset_down:
    sequence:
      - service: input_slider.select_value
        data_template:
          entity_id: input_slider.option_target_temperature_offset
          value: '{{ states.input_slider.option_target_temperature_offset.state | int - 1 }}'

  target_temperature_offset_up:
    sequence:
      - service: input_slider.select_value
        data_template:
          entity_id: input_slider.option_target_temperature_offset
          value: '{{ states.input_slider.option_target_temperature_offset.state | int + 1 }}'



input_boolean:
##########################################
########## STORED VARIABLES ##############
##########################################
  var_indoor_temp_hot:
  var_indoor_temp_very_warm:
  var_indoor_temp_warm:
  var_indoor_temp_ok:
  var_indoor_temp_cool:
  var_indoor_temp_cold:

  var_indoor_humidity_high:
  var_indoor_humidity_ok:
  var_indoor_humidity_low:



#********** Temperature Input Sliders ***********#
input_slider:

  var_indoor_temp_time_of_day:
    min: -3
    max: 2
    step: 1

  var_indoor_temp_mike_at_work:
    min: -1
    max: 4
    step: 1

  var_indoor_temp_hot:
    name: Indoor Temp (HOT)
    initial: 80
    min: 65
    max: 85
    step: 1

  var_indoor_temp_very_warm:
    name: Indoor Temp (VERY WARM)
    initial: 78
    min: 65
    max: 85
    step: 1

  var_indoor_temp_warm:
    name: Indoor Temp (WARM)
    initial: 76
    min: 65
    max: 85
    step: 1

  var_indoor_temp_ok:
    name: Indoor Temp (OK)
    initial: 74
    min: 65
    max: 85
    step: 1

  var_indoor_temp_cool:
    name: Indoor Temp (COOL)
    initial: 72
    min: 65
    max: 85
    step: 1

  option_target_temperature_offset:
    name: Target Temperature Offset
    min: -5
    max: 5
    step: 1

##########################################
############### GROUPS ###################
##########################################
group:

  indoor_temperature_range_mode:
    name: "Indoor Temperature Range Mode"
    entities:
      - input_boolean.var_indoor_temp_hot
      - input_boolean.var_indoor_temp_very_warm
      - input_boolean.var_indoor_temp_warm
      - input_boolean.var_indoor_temp_ok
      - input_boolean.var_indoor_temp_cool
      - input_boolean.var_indoor_temp_cold

  automation_temperature_range_mode:
    entities:
      - automation.set_indoor_temp_hot
      - automation.set_indoor_temp_very_warm
      - automation.set_indoor_temp_warm
      - automation.set_indoor_temp_ok
      - automation.set_indoor_temp_cool
      - automation.set_indoor_temp_cold
      - automation.indoor_temp_hot
      - automation.indoor_temp_very_warm
      - automation.indoor_temp_warm
      - automation.indoor_temp_ok
      - automation.indoor_temp_cool
      - automation.indoor_temp_cold
      - automation.reset_option_target_temperature_offset
      - automation.reset_var_indoor_temp_time_of_day
      - automation.reset_var_indoor_temp_mike_at_work
      - automation.indoor_temp_time_12am
      - automation.indoor_temp_time_10am
      - automation.indoor_temp_time_4pm
      - automation.indoor_temp_time_7pm
      - automation.indoor_temp_time_9pm
      - automation.indoor_temp_mike_at_work
      - automation.indoor_temp_mike_not_at_work
      - automation.set_indoor_humidity_low
      - automation.set_indoor_humidity_ok
      - automation.set_indoor_humidity_high

  homeassistant_temperature_range_mode:
    entities:
      - input_slider.var_indoor_temp_hot
      - input_slider.var_indoor_temp_very_warm
      - input_slider.var_indoor_temp_warm
      - input_slider.var_indoor_temp_ok
      - input_slider.var_indoor_temp_cool
      - input_slider.var_indoor_temp_time_of_day
      - input_slider.var_indoor_temp_mike_at_work

  options_temperature_range_mode:
    name: "Environment"
    entities:
      - sensor.indoor_temp_hot_level
      - sensor.indoor_temp_very_warm_level
      - sensor.indoor_temp_warm_level
      - sensor.indoor_temp_ok_level
      - sensor.indoor_temp_cool_level
      - sensor.indoor_temp_time_of_day_offset
      - sensor.indoor_temp_mike_at_work_offset
      - input_slider.option_target_temperature_offset
#
  script_temperature_range_mode:
    entities:
      - script.target_temperature_offset_up
      - script.target_temperature_offset_down
