homeassistant:
  customize:
    script.target_temperature_offset_down:
      emulated_hue: true
      emulated_hue_name: "Temperature Down"
    script.target_temperature_offset_up:
      emulated_hue: true
      emulated_hue_name: "Temperature Up"
# switch:
# lights:
# binary_sensor:
# sensor:

automation:
##########################################
########## SET INDOOR TEMP RANGE #########
##########################################
  - alias: set_indoor_temp_hot
    trigger:
      - platform: template
        value_template: '{% if  states.sensor.indoor_temperature.state  %}{% if ( states.sensor.indoor_temperature.state | float - states.input_slider.option_target_temperature_offset.state | float ) > states.input_slider.option_indoor_temp_hot.state | float %}true{%endif%}{%endif%}'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.var_indoor_temp_hot

  - alias: set_indoor_temp_very_warm
    trigger:
      - platform: template
        value_template: '{% if  states.sensor.indoor_temperature.state  %}{% if ( states.sensor.indoor_temperature.state | float - states.input_slider.option_target_temperature_offset.state | float ) > states.input_slider.option_indoor_temp_very_warm.state | float and ( states.sensor.indoor_temperature.state | float - states.input_slider.option_target_temperature_offset.state | float ) < states.input_slider.option_indoor_temp_hot.state | float %}true{%endif%}{%endif%}'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.var_indoor_temp_very_warm

  - alias: set_indoor_temp_warm
    trigger:
      - platform: template
        value_template: '{% if  states.sensor.indoor_temperature.state  %}{% if ( states.sensor.indoor_temperature.state | float - states.input_slider.option_target_temperature_offset.state | float ) > states.input_slider.option_indoor_temp_warm.state | float and ( states.sensor.indoor_temperature.state | float - states.input_slider.option_target_temperature_offset.state | float ) < states.input_slider.option_indoor_temp_very_warm.state | float %}true{%endif%}{%endif%}'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.var_indoor_temp_warm

  - alias: set_indoor_temp_ok
    trigger:
      - platform: template
        value_template: '{% if  states.sensor.indoor_temperature.state  %}{% if ( states.sensor.indoor_temperature.state | float - states.input_slider.option_target_temperature_offset.state | float ) > states.input_slider.option_indoor_temp_ok.state | float and ( states.sensor.indoor_temperature.state | float - states.input_slider.option_target_temperature_offset.state | float ) < states.input_slider.option_indoor_temp_warm.state | float %}true{%endif%}{%endif%}'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.var_indoor_temp_ok

  - alias: set_indoor_temp_cool
    trigger:
      - platform: template
        value_template: '{% if  states.sensor.indoor_temperature.state  %}{% if ( states.sensor.indoor_temperature.state | float - states.input_slider.option_target_temperature_offset.state | float ) > states.input_slider.option_indoor_temp_cool.state | float and ( states.sensor.indoor_temperature.state | float - states.input_slider.option_target_temperature_offset.state | float ) < states.input_slider.option_indoor_temp_ok.state | float %}true{%endif%}{%endif%}'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.var_indoor_temp_cool

  - alias: set_indoor_temp_cold
    trigger:
      - platform: template
        value_template: '{% if  states.sensor.indoor_temperature.state  %}{% if ( states.sensor.indoor_temperature.state | float - states.input_slider.option_target_temperature_offset.state | float ) < states.input_slider.option_indoor_temp_cool.state | float %}true{%endif%}{%endif%}'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.var_indoor_temp_cold


##########################################
########## SET OTHER INPUT BOOLEANS ######
##########################################
  - alias: indoor_temp_hot
    trigger:
      - platform: state
        entity_id: input_boolean.var_indoor_temp_hot
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_very_warm
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_warm
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_ok
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_cool
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_cold

  - alias: indoor_temp_very_warm
    trigger:
      - platform: state
        entity_id: input_boolean.var_indoor_temp_very_warm
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_hot
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_warm
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_ok
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_cool
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_cold

  - alias: indoor_temp_warm
    trigger:
      - platform: state
        entity_id: input_boolean.var_indoor_temp_warm
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_hot
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_very_warm
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_ok
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_cool
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_cold

  - alias: indoor_temp_ok
    trigger:
      - platform: state
        entity_id: input_boolean.var_indoor_temp_ok
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_hot
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_very_warm
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_warm
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_cool
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_cold

  - alias: indoor_temp_cool
    trigger:
      - platform: state
        entity_id: input_boolean.var_indoor_temp_cool
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_hot
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_very_warm
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_warm
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_ok
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_cold


  - alias: indoor_temp_cold
    trigger:
      - platform: state
        entity_id: input_boolean.var_indoor_temp_cold
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_hot
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_very_warm
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_warm
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_ok
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_indoor_temp_cool



##########################################
########## SCRIPTS #######################
##########################################
script:
  target_temperature_offset_down:
    sequence:
      - service: input_slider.select_value
        data_template:
          entity_id: input_slider.option_target_temperature_offset
          value: '{{ states.input_slider.option_target_temperature_offset | int - 1 }}'

  target_temperature_offset_up:
    sequence:
      - service: input_slider.select_value
        data_template:
          entity_id: input_slider.option_target_temperature_offset
          value: '{{ states.input_slider.option_target_temperature_offset | int + 1 }}'



input_boolean:
##########################################
########## STORED VARIABLES ##############
##########################################
  var_indoor_temp_hot:
  var_indoor_temp_very_warm:
  var_indoor_temp_warm:
  var_indoor_temp_ok:
  var_indoor_temp_cool:
  var_indoor_temp_cold:




#********** Temperature Input Sliders ***********#
input_slider:
  option_indoor_temp_hot:
    name: Indoor Temp (HOT)
    initial: 80
    min: 65
    max: 85
    step: 1

  option_indoor_temp_very_warm:
    name: Indoor Temp (VERY WARM)
    initial: 78
    min: 65
    max: 85
    step: 1

  option_indoor_temp_warm:
    name: Indoor Temp (WARM)
    initial: 76
    min: 65
    max: 85
    step: 1

  option_indoor_temp_ok:
    name: Indoor Temp (OK)
    initial: 74
    min: 65
    max: 85
    step: 1

  option_indoor_temp_cool:
    name: Indoor Temp (COOL)
    initial: 72
    min: 65
    max: 85
    step: 1

  option_target_temperature_offset:
    name: Target Temperature Offset
    min: -5
    max: 5
    step: 1

##########################################
############### GROUPS ###################
##########################################
group:

  indoor_temperature_range_mode:
    name: "Indoor Temperature Range Mode"
    entities:
      - input_boolean.var_indoor_temp_hot
      - input_boolean.var_indoor_temp_very_warm
      - input_boolean.var_indoor_temp_warm
      - input_boolean.var_indoor_temp_ok
      - input_boolean.var_indoor_temp_cool
      - input_boolean.var_indoor_temp_cold

  automation_temperature_range_mode:
    entities:
      - automation.set_indoor_temp_hot
      - automation.set_indoor_temp_very_warm
      - automation.set_indoor_temp_warm
      - automation.set_indoor_temp_ok
      - automation.set_indoor_temp_cool
      - automation.set_indoor_temp_cold
      - automation.indoor_temp_hot
      - automation.indoor_temp_very_warm
      - automation.indoor_temp_warm
      - automation.indoor_temp_ok
      - automation.indoor_temp_cool
      - automation.indoor_temp_cold
#
#
#   homeassistant_template:
#     entities:
#
#
  options_temperature_range_mode:
    name: "Environment"
    entities:
      - input_slider.option_indoor_temp_hot
      - input_slider.option_indoor_temp_very_warm
      - input_slider.option_indoor_temp_warm
      - input_slider.option_indoor_temp_ok
      - input_slider.option_indoor_temp_cool
      - input_slider.option_target_temperature_offset
#
  script_temperature_range_mode:
    entities:
      - script.target_temperature_offset_up
      - script.target_temperature_offset_down
