sensor:
##########################################
############### SENSORS ##################
##########################################
  - platform: coinmarketcap
  - platform: template
    sensors:
      bitcoin_percent_change_24h:
        friendly_name: 'Percent Change 24h'
        value_template: >-
            {%- if states.sensor.bitcoin %}
                {{ states.sensor.bitcoin.attributes.percent_change_24h }}
            {% else %}

            {%- endif %}
        unit_of_measurement: '%'

      bitcoin_percent_change_7d:
        friendly_name: 'Percent Change 7d'
        value_template: >-
            {%- if states.sensor.bitcoin %}
                {{ states.sensor.bitcoin.attributes.percent_change_7d }}
            {% else %}

            {%- endif %}
        unit_of_measurement: '%'

automation:
##########################################
############### NOTIFICATIONS ############
##########################################
  - alias: Bitcoin Up
    trigger:
      - platform: numeric_state
        entity_id: sensor.bitcoin_percent_change_24h
        above: 2
      - platform: template
        value_template: 'states.sensor.bitcoin.state | round(0) > states.input_slider.var_last_known_bitcoin_price.state + states.input_slider.var_bitcoin_price_notification_tolerance.state'
    action:
      - service: script.notify2
        data_template:
          telegram_message: |
            *Bitcoin: ${{ states.sensor.bitcoin.state | round(0) }}*
            24h: {{ states.sensor.bitcoin_percent_change_24h.state | round(1) }}%
            7d:  {{ states.sensor.bitcoin_percent_change_7d.state | round(1) }}%
          telegram_url: http://bitcoincharts.com/charts/chart.png?width=848&height=480&m=bitstampUSD&SubmitButton=Draw&r=2&i=5-min&c=0&s=&e=&Prev=&Next=&t=C&b=&a1=&m1=10&a2=&m2=25&x=0&i1=&i2=&i3=&i4=&v=1&cv=0&ps=0&l=0&p=0&
          flood_color: "cyan"
          blink_color: "gold"
          blink_color2: "green"
          chromecast_entity_id: media_player.vtv_chromecast
          chromecast_link: http://bitcoincharts.com/charts/chart.png?width=848&height=480&m=bitstampUSD&SubmitButton=Draw&r=2&i=5-min&c=0&s=&e=&Prev=&Next=&t=C&b=&a1=&m1=10&a2=&m2=25&x=0&i1=&i2=&i3=&i4=&v=1&cv=0&ps=0&l=0&p=0&
          tts_entity_id: group.tts_devices
          tts_sound: 'intercom_ds9.mp3'
          tts_message: "Bitcoin's up! The current bitcoin price is {{ states.sensor.bitcoin.state | round(0) }}"
      - service: input_slider.select_value
        data_template:
          entity_id: input_slider.var_last_known_bitcoin_price
          value: '{{ states.sensor.bitcoin.state | round(0) }}'

  - alias: Bitcoin Down
    trigger:
      - platform: numeric_state
        entity_id: sensor.bitcoin_percent_change_24h
        below: -2
      - platform: template
        value_template: 'states.sensor.bitcoin.state | round(0) < states.input_slider.var_last_known_bitcoin_price.state - states.input_slider.var_bitcoin_price_notification_tolerance.state'
    action:
      - service: script.notify2
        data_template:
          telegram_message: |
            *Bitcoin: ${{ states.sensor.bitcoin.state | round(2) }}*
            24h: {{ states.sensor.bitcoin_percent_change_24h.state | round(1) }}%
            7d:  {{ states.sensor.bitcoin_percent_change_7d.state | round(1) }}%
          telegram_url: http://bitcoincharts.com/charts/chart.png?width=848&height=480&m=bitstampUSD&SubmitButton=Draw&r=2&i=5-min&c=0&s=&e=&Prev=&Next=&t=C&b=&a1=&m1=10&a2=&m2=25&x=0&i1=&i2=&i3=&i4=&v=1&cv=0&ps=0&l=0&p=0&
          flood_color: "cyan"
          blink_color: "gold"
          blink_color2: "red"
          chromecast_entity_id: media_player.vtv_chromecast
          chromecast_link: http://bitcoincharts.com/charts/chart.png?width=848&height=480&m=bitstampUSD&SubmitButton=Draw&r=2&i=5-min&c=0&s=&e=&Prev=&Next=&t=C&b=&a1=&m1=10&a2=&m2=25&x=0&i1=&i2=&i3=&i4=&v=1&cv=0&ps=0&l=0&p=0&
          tts_entity_id: group.tts_devices
          tts_sound: 'intercom_ds9.mp3'
          tts_message: "Bitcoin's down! The current bitcoin price is {{ states.sensor.bitcoin.state | round(0) }}"
      - service: input_slider.select_value
        data_template:
          entity_id: input_slider.var_last_known_bitcoin_price
          value: '{{ states.sensor.bitcoin.state | round(0) }}'

input_slider:
##########################################
########## STORED VARIABLES ##############
##########################################
  var_last_known_bitcoin_price:
    min: 0
    max: 999999
    step: 1

  option_bitcoin_price_notification_tolerance:
    min: 0
    max: 1000
    step: 10
    initial: 10
##########################################
########## OPTIONS #######################
##########################################
