# homeassistant:
#   customize:
# switch:
# lights:
# binary_sensor:
# sensor:

automation:
##########################################
########## MQTT SUBSCRIPTIONS ############
##########################################

  - alias: toggle_mqtt_entertainment_center_power
    trigger:
      - platform: mqtt
        topic: device/eventghost/ec_power
        payload: "toggle"
    action:
      - service: switch.toggle
        entity_id: switch.sonoff_entertainment_center
      ## Toggles off lights if after 12pm
      - condition: time
        after: "00:00:00"
      - condition: sun
        before: sunrise
      - delay: "00:00:02"
      - service: light.turn_off
        entity_id: group.ambient_lights
      - delay: "00:00:05"
      - service: scene.turn_on
        entity_id: scene.10m_off



  - alias: toggle_mqtt_chromecast_playpause
    trigger:
      - platform: mqtt
        topic: device/eventghost/play_pause
        payload: "toggle"
    action:
      - service: media_player.media_play_pause
        entity_id: media_player.vtv_chromecast
      - service: script.flash_light
        data:
          flash_color: "cyan"
          entity_id: group.tv_lights



  - alias: toggle_mqtt_chromecast_stop
    trigger:
      - platform: mqtt
        topic: device/eventghost/stop
        payload: "toggle"
    action:
      - service: media_player.media_stop
        entity_id: media_player.vtv_chromecast
      - service: script.flash_light
        data:
          flash_color: "cyan"
          entity_id: group.tv_lights



  - alias: toggle_mqtt_chromecast_prev
    trigger:
      - platform: mqtt
        topic: device/eventghost/prev
        payload: "1"
    action:
      - service: media_player.media_previous_track
        entity_id: media_player.vtv_chromecast
      - service: script.flash_light
        data:
          flash_color: "cyan"
          entity_id: group.tv_lights



  - alias: toggle_mqtt_chromecast_next
    trigger:
      - platform: mqtt
        topic: device/eventghost/next
        payload: "1"
    action:
      - service: media_player.media_next_track
        entity_id: media_player.vtv_chromecast
      - service: script.flash_light
        data:
          flash_color: "cyan"
          entity_id: group.tv_lights



  - alias: mqtt_flash_cyan
    trigger:
      - platform: mqtt
        topic: device/hass/breathe_light
        payload: "1"
    action:
      - service: script.flash_light
        data:
          flash_color: "cyan"
          entity_id: group.tv_lights



  - alias: button
    trigger:
    - platform: mqtt
      topic: device/eventghost/button
    action:
    - service: script.eventghost_button
      data_template:
        button: '{{ trigger.payload }}'

  - alias: button_long
    trigger:
    - platform: mqtt
      topic: device/eventghost/button_long
    action:
    - service: script.eventghost_button_long
      data_template:
        button: '{{ trigger.payload }}'

##########################################
########## AUTOMATIONS ###################
##########################################




##########################################
########## SCRIPTS #######################
##########################################
script:
  eventghost_button:
    sequence:
    - service_template: >
        {% if button | int == 1 %}
          scene.turn_on
        {% elif button | int == 2  %}
          scene.turn_on
        {% elif button | int == 3  %}
          scene.turn_on
        {% elif button | int == 4  %}
          scene.turn_on
        {% elif button | int == 5  %}
          scene.turn_on
        {% elif button | int == 6  %}
          scene.turn_on
        {% endif %}
      data_template:
        entity_id: >
          {% if button | int == 1 %}
            scene.day
          {% elif button | int == 2  %}
            scene.night_cyan
          {% elif button | int == 3  %}
            scene.night_blue
          {% elif button | int == 4  %}
            scene.night_red
          {% elif button | int == 5  %}
            scene.chill
          {% elif button | int == 6  %}
            scene.chill_2
          {% endif %}


  eventghost_button_long:
    sequence:
    - service_template: >
        {% if button | int == 1 %}
          scene.turn_on
        {% elif button | int == 2  %}
          scene.turn_on
        {% elif button | int == 3  %}
          scene.turn_on
        {% elif button | int == 4  %}
          scene.turn_on
        {% elif button | int == 5  %}
          scene.turn_on
        {% elif button | int == 6  %}
          script.turn_on
        {% endif %}
      data_template:
        entity_id: >
          {% if button | int == 1 %}
            scene.off
          {% elif button | int == 2  %}
            scene.night_computer
          {% elif button | int == 3  %}
            scene.night_computer_red
          {% elif button | int == 4  %}
            scene.off
          {% elif button | int == 5  %}
            scene.off
          {% elif button | int == 6  %}
            script.10m_flood_day_bright
          {% endif %}



# input_boolean:
##########################################
########## STORED VARIABLES ##############
##########################################



##########################################
########## OPTIONS #######################
##########################################


##########################################
############### GROUPS ###################
##########################################
group:
  automation_bose_remote:
    entities:
      - automation.toggle_mqtt_entertainment_center_power
      - automation.toggle_mqtt_chromecast_playpause
      - automation.toggle_mqtt_chromecast_stop
      - automation.toggle_mqtt_chromecast_prev
      - automation.toggle_mqtt_chromecast_next
      - automation.mqtt_flash_cyan
      - automation.button
      - automation.button_long

  script_bose_remote:
    entities:
      - script.eventghost_button
      - script.eventghost_button_long
