# homeassistant:
#   customize:
    # input_boolean.template:
    #   emulated_hue: true
    #   emulated_hue_name: "Template Name"
# switch:
# lights:
# binary_sensor:
sensor:
  - platform: template
    sensors:
      upcoming_packers_event:
        friendly_name: 'Packers Game'
        value_template: >-
            {%- if states.calendar.green_bay_packers %}
                {{ states.calendar.green_bay_packers.attributes.message }}
            {% else %}

            {%- endif %}

      upcoming_packers_start_time:
        value_template: >-
            {%- if states.calendar.green_bay_packer %}
                {{ states.calendar.green_bay_packers.attributes.start_time }}
            {% else %}

            {%- endif %}

      upcoming_bears_event:
        friendly_name: 'Bears Game'
        value_template: >-
            {%- if states.calendar.chicago_bears %}
                {{ states.calendar.chicago_bears.attributes.message }}
            {% else %}

            {%- endif %}

      upcoming_bears_start_time:
        value_template: >-
            {%- if states.calendar.chicago_bears %}
                {{ states.calendar.chicago_bears.attributes.start_time }}
            {% else %}

            {%- endif %}

      upcoming_twit_event:
        friendly_name: 'Twit.tv '
        value_template: >-
            {%- if states.calendar.twit_live_schedule %}
                {{ states.calendar.twit_live_schedule.attributes.message }}
            {% else %}

            {%- endif %}

      upcoming_twit_start_time:
        value_template: >-
            {%- if states.calendar.twit_live_schedule %}
                {{ states.calendar.twit_live_schedule.attributes.start_time }}
            {% else %}

            {%- endif %}

automation:
##########################################
########## NOTIFICATIONS #################
##########################################



##########################################
########## AUTOMATIONS ###################
##########################################
  - alias: mike_at_work
    trigger:
      - platform: time
        minutes: 01
        seconds: 00
      - platform: state
        entity_id: input_boolean.var_mike_home
        from: 'on'
        to: 'off'
    condition:
      - condition: template
        value_template: '{{ states.sensor.time.state[:2] | int >= states.input_slider.var_mike_work_start_hour.state | int  }}'
      - condition: template
        value_template: '{{ states.sensor.time.state[:2] | int < states.input_slider.var_mike_work_end_hour.state | int  }}'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: input_boolean.var_mike_home
        state: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.var_mike_at_work

  - alias: mike_not_at_work
    trigger:
      - platform: time
        minutes: 01
        seconds: 00
      - platform: state
        entity_id: input_boolean.var_mike_home
        from: 'off'
        to: 'on'
    condition:
      condition: or
      conditions:
      - condition: template
        value_template: '{{ states.sensor.time.state[:2] | int < states.input_slider.var_mike_work_start_hour.state | int  }}'
      - condition: template
        value_template: '{{ states.sensor.time.state[:2] | int >= states.input_slider.var_mike_work_end_hour.state | int  }}'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.var_mike_at_work


##########################################
########## SCRIPTS #######################
##########################################
# script:





##########################################
########## STORED VARIABLES ##############
##########################################
input_boolean:
  var_mike_at_work:
    initial: 'off'

input_slider:
  var_mike_work_start_hour:
    initial: 9
    min: 0
    max: 23
    step: 1

  var_mike_work_end_hour:
    initial: 17
    min: 0
    max: 23
    step: 1



##########################################
########## OPTIONS #######################
##########################################


##########################################
############### GROUPS ###################
##########################################
group:
  google_calandars:
    name: "Google Calendars"
    entities:
      - calendar.default
      - calendar.twit_live_schedule
      - calendar.green_bay_packers
      - calendar.chicago_bears
      - calendar.subspace_radio
      - calendar.rev_20
      - calendar.stardates

  upcoming_events:
    name: "Upcoming Events"
    entities:
      - sensor.upcoming_packers_event
      - sensor.upcoming_packers_start_time
      - sensor.upcoming_bears_event
      - sensor.upcoming_bears_start_time
      - sensor.upcoming_twit_event
      - sensor.upcoming_twit_start_time

  automation_calandar:
    entities:
      - automation.mike_at_work
      - automation.mike_not_at_work

  homeassistant_calandar:
    entities:
      - input_boolean.var_mike_at_work
      - input_boolean.var_mike_work_start_hour
      - input_boolean.var_mike_work_end_hour

  # options_calandar:
  #   entities:


  # script_calandar:
  #   entities:
