# homeassistant:
#   customize:
    # input_boolean.template:
    #   emulated_hue: true
    #   emulated_hue_name: "Template Name"
# switch:
# lights:
# binary_sensor:
# sensor:

telegram_bot:
  platform: polling
  api_key: !secret telegram_api_key
  allowed_chat_ids:
    - 343498992 # @liberty_minded user
    - 240044026 # IFTTT
    - -296159061 # @ vHome group

automation:
##########################################
########## AUTOMATIONS ###################
##########################################
  - alias: telegram_command_notify2_tts
    trigger:
      - platform: event
        event_type: telegram_command
        event_data:
          command: '/notify2_tts'
      - platform: event
        event_type: telegram_command
        event_data:
          command: '/s'
    action:
      - service: script.notify2
        data_template:
          tts_message: |
            {% set args_modified = trigger.event.data["args"] | join(', ') | replace(",","") %}
            {{ args_modified | string }}


##########################################
########## SCRIPTS #######################
##########################################
# script:




# input_boolean:
##########################################
########## STORED VARIABLES ##############
##########################################



##########################################
########## OPTIONS #######################
##########################################


##########################################
############### GROUPS ###################
##########################################
group:
  automation_change_me:
    entities:
      - automation.telegram_command_notify2_tts
      # - automation.
      # - automation.
      # - automation.
      # - automation.
      # - automation.
      # - automation.
      # - automation.

#   backend_change_me:
#     entities:
#       - input_boolean.

#   hidden_change_me:
#     entities:
#       - input_boolean.

#   options_change_me:
#     entities:
#       - input_boolean.

#   script_change_me:
#     entities:
#       - script.
