# homeassistant:
#   customize:
    # input_boolean.template:
    #   emulated_hue: true
    #   emulated_hue_name: "Template Name"
# switch:
# lights:
# binary_sensor:
sensor:
  - platform: template
    sensors:
##########################################
########## USER SETTINGS #################
##########################################
## NOTE: Only Change the 'User Settings'. Everything else is dynamicaly calculated using these variables.
      # Exact time I leave the house for work
      var_mike_leave_for_work_hour:
        value_template: '17'
      var_mike_leave_for_work_minute:
        value_template: '45'

      # Exact hours that work starts and ends
      var_mike_work_start_hour:
        value_template: '18'
      var_mike_work_end_hour:
        value_template: '5'

      # Exact Days that I am at work. If Third Shift, include the day that you get off last.
      var_mike_work_week:
        value_template: "['mon', 'tue', 'wed', 'thu', 'fri']"
      var_mike_work_week_third_shift:
        value_template: 'true'
      var_mike_work_week_third_shift_first_day:
        value_template: "mon"
      var_mike_work_week_third_shift_last_day:
        value_template: "fri"


##########################################
########## SENSORS #######################
##########################################


      # Sensor: Determains if Mike "should" be at work based off time and day of week.
      mike_at_work:
        entity_id:
          - sensor.now_day
          - sensor.now_hour
        value_template: >
          {% set work_week = states.sensor.var_mike_work_week.state %}
          {% set third_shift = states.sensor.var_mike_work_week_third_shift.state %}
          {% set third_shift_first_day = states.sensor.var_mike_work_week_third_shift_first_day.state %}
          {% set third_shift_last_day = states.sensor.var_mike_work_week_third_shift_last_day.state %}

          {% set today = states.sensor.now_day.state %}
          {% set hour = states.sensor.now_hour.state %}

          {####### 3rd Shift ##########}
          {% if third_shift %}
            {####### Check Time ##########}
            {% if hour | int >= states.sensor.var_mike_work_start_hour.state | int or hour | int < states.sensor.var_mike_work_end_hour.state | int %}
              {####### Check Day ##########}
              {% if today in work_week %}
                {###### Check First/Last Day ######}
                {% if today ==  third_shift_first_day and hour | int < states.sensor.var_mike_work_start_hour.state | int %}
                  off
                {% elif today ==  third_shift_last_day and hour | int >= states.sensor.var_mike_work_end_hour.state | int %}
                  off
                {% else %}
                  on
                {% endif %}
              {% else %}
                off
              {% endif %}
            {% else %}
              off
            {% endif %}

          {####### Day Shift ##########}
          {% else %}
            {####### Check Time ##########}
            {% if hour | int >= states.sensor.var_mike_work_start_hour.state | int and hour | int < states.sensor.var_mike_work_end_hour.state | int %}
              {####### Check Day ##########}
              {% if today in work_week %}
                on
              {% else %}
                off
              {% endif %}
            {% else %}
              off
            {% endif %}
          {% endif %}

      # Sensor: Determains if today is a work day for Mike based off day of week.
      mike_work_day:
        entity_id:
          - sensor.now_day
        value_template: >
          {% set work_week = states.sensor.var_mike_work_week.state %}
          {% set third_shift = states.sensor.var_mike_work_week_third_shift.state %}
          {% set third_shift_last_day = states.sensor.var_mike_work_week_third_shift_last_day.state %}
          {% set today = states.sensor.now_day.state %}

          {% if today in work_week %}
            {% if third_shift %}
              {% if today == third_shift_last_day %}
                off
              {% else %}
                on
              {% endif %}
            {% else %}
              on
            {% endif %}
          {% else %}
            off
          {% endif %}

automation:
##########################################
########## MIKE - LEAVE FOR WORK #########
##########################################

  # Option: Mike Prework Timebased Lights Turn ON
  - alias: mike_prework_timebased_lights_on
    trigger:
      - platform: state
        entity_id: sensor.mike_work_day
        to: 'on'
      - platform: state
        entity_id: input_boolean.mode_normal
        to: 'on'
    condition:
      - condition: state
        entity_id: sensor.mike_work_day
        state: 'on'
    action:
      # Turn on Prework Timebased Lights
      - service: input_boolean.turn_on
        entity_id: input_boolean.option_notify2_prework_timebased_lights


  # Option: Mike Prework Timebased Lights Turn OFF
  - alias: mike_prework_timebased_lights_off
    trigger:
      - platform: state
        entity_id: sensor.mike_work_day
        to: 'off'
    action:
      # Turn off Prework Timebased Lights
      - service: input_boolean.turn_off
        entity_id: input_boolean.option_notify2_prework_timebased_lights




# T-2h
  - alias: leave_for_work_t2h
    trigger:
      - platform: template
        value_template: >
          {% if states.sensor.now_hour.state| int == states.sensor.var_mike_leave_for_work_hour.state | int - 2 %}
            {% if states.sensor.now_minute.state | int == states.sensor.var_mike_leave_for_work_minute.state | int %}
              true
            {% endif %}
          {% endif %}
    condition:
      - condition: state
        entity_id: input_boolean.option_notify2_prework_timebased_lights
        state: 'on'
    action:
      # Turn On - Prework Mode
      - service: input_boolean.turn_on
        entity_id: input_boolean.option_mode_prework

      - service: script.notify2
        data_template:
          flood_color: "red"
          entity_id: group.timebased_flood_lights
          delay: "00:00:01"
          next_scene: 'prework_cyan'
          tts_entity_id: group.tts_devices
          tts_sound: 'isaac/weapon_room.mp3'
          tts_sound_delay: '00:00:05'
          tts_message: "Get ready to leave for work in. T minus 2 hours. Your iPhone is at. {{ states('sensor.iphone6s_battery') | int }}%. and your Watch is at. {{ states('sensor.watch_battery') | int }}%. I  sent your pre work checklist to telegram for review."
          tts_pause_delay: '00:00:00'
          telegram_message: |
            T-2h Batteries:
            {% if states("sensor.iphone6s_battery") | int == 100 %}*{% endif %}iPhone: {{ states("sensor.iphone6s_battery") | int }}%{% if states("sensor.iphone6s_battery") | int == 100 %}*{% endif %}
            {% if states("sensor.watch_battery") | int == 100 %}*{% endif %}Watch: {{ states("sensor.watch_battery") | int }}%{% if states("sensor.watch_battery") | int == 100 %}*{% endif %}

            T-2h Checklist:
            - Shower
            - Clear Eyes
            - Deodorant
            - Cologne
            - Vitamins
            - Clean up
            - Ready Lunch
            - Eat Something


# T-1h
  - alias: leave_for_work_t1h
    trigger:
      - platform: template
        value_template: >
          {% if states.sensor.now_hour.state| int == states.sensor.var_mike_leave_for_work_hour.state | int - 1 %}
            {% if states.sensor.now_minute.state | int == states.sensor.var_mike_leave_for_work_minute.state | int %}
              true
            {% endif %}
          {% endif %}
    condition:
      - condition: state
        entity_id: input_boolean.option_notify2_prework_timebased_lights
        state: 'on'
    action:
      - service: script.notify2
        data_template:
          flood_color: "red"
          entity_id: group.timebased_flood_lights
          delay: "00:00:01"
          next_scene: 'prework_blue'
          tts_entity_id: group.tts_devices
          tts_sound: 'isaac/weapon_room.mp3'
          tts_sound_delay: '00:00:05'
          tts_message: "Leave for work in. T minus 1 hour"
          tts_pause_delay: '00:00:00'


# T-30m
  - alias: leave_for_work_t30m
    trigger:
      - platform: template
        value_template: >
          {% if states.sensor.now_hour.state| int == states.sensor.var_mike_leave_for_work_hour.state | int %}
            {% if states.sensor.now_minute.state | int == states.sensor.var_mike_leave_for_work_minute.state | int - 30 %}
              true
            {% endif %}
          {% endif %}
    condition:
      - condition: state
        entity_id: input_boolean.option_notify2_prework_timebased_lights
        state: 'on'
    action:
      - service: script.notify2
        data_template:
          flood_color: "red"
          entity_id: group.timebased_flood_lights
          delay: "00:00:01"
          next_scene: 'prework_purple'
          tts_entity_id: group.tts_devices
          tts_sound: 'isaac/secret_room_find.mp3'
          tts_sound_delay: '00:00:04'
          tts_message: "Leave for work in. T minus 30 minutes. I  sent your pre work checklist to telegram for review."
          tts_pause_delay: '00:00:00'
          telegram_message: |
            T-30m Re:
            - Fill e-Cig
            - Download Podcasts
            - Ready EDC Backpack
            - Grab Lunch
            - Check Shirt Stains
            - Check Clean Shave
            - Brush Teeth

# T-15m
  - alias: leave_for_work_t15m
    trigger:
      - platform: template
        value_template: >
          {% if states.sensor.now_hour.state| int == states.sensor.var_mike_leave_for_work_hour.state | int %}
            {% if states.sensor.now_minute.state | int == states.sensor.var_mike_leave_for_work_minute.state | int - 15 %}
              true
            {% endif %}
          {% endif %}
    condition:
      - condition: state
        entity_id: input_boolean.option_notify2_prework_timebased_lights
        state: 'on'
    action:
      - service: script.notify2
        data_template:
          flood_color: "red"
          entity_id: group.timebased_flood_lights
          delay: "00:00:01"
          next_scene: 'prework_red'
          tts_entity_id: group.tts_devices
          tts_sound: 'isaac/secret_room_find.mp3'
          tts_sound_delay: '00:00:04'
          tts_message: "Leave for work in. T minus 15 minutes."
          tts_pause_delay: '00:00:00'


# T-10m
  - alias: leave_for_work_t10m
    trigger:
      - platform: template
        value_template: >
          {% if states.sensor.now_hour.state| int == states.sensor.var_mike_leave_for_work_hour.state | int %}
            {% if states.sensor.now_minute.state | int == states.sensor.var_mike_leave_for_work_minute.state | int - 10 %}
              true
            {% endif %}
          {% endif %}
    condition:
      - condition: state
        entity_id: input_boolean.option_notify2_prework_timebased_lights
        state: 'on'
    action:
      - service: script.notify2
        data_template:
          flood_color: "red"
          entity_id: group.timebased_flood_lights
          delay: "00:00:01"
          next_scene: 'prework_t10m'
          tts_entity_id: group.tts_devices
          tts_sound: 'isaac/isaacbosswin.mp3'
          tts_sound_delay: '00:00:05'
          tts_message: |
            Leave for work in. T minus 10 minutes.
            Do not forget the following items:
              - Cigarettes and Vape
              - Wallet
              - Keys
              - ID Badge
              - iPhone
              - and your Apple Watch
          tts_pause_delay: '00:00:00'
          telegram_message: |
            T-10m DON'T FORGET:
            - Cigarettes/Lighter/eCig
            - Wallet
            - Keys
            - ID Badge
            - Phone & Watch


# T-5m
  - alias: leave_for_work_t5m
    trigger:
      - platform: template
        value_template: >
          {% if states.sensor.now_hour.state| int == states.sensor.var_mike_leave_for_work_hour.state | int %}
            {% if states.sensor.now_minute.state | int == states.sensor.var_mike_leave_for_work_minute.state | int - 5 %}
              true
            {% endif %}
          {% endif %}
    condition:
      - condition: state
        entity_id: input_boolean.option_notify2_prework_timebased_lights
        state: 'on'
    action:
      - service: script.notify2
        data_template:
          flood_color: "red"
          entity_id: group.timebased_flood_lights
          delay: "00:00:01"
          next_scene: 'day_bright'
          tts_entity_id: group.tts_devices
          tts_sound: 'isaac/secret_room_find.mp3'
          tts_sound_delay: '00:00:04'
          tts_message: "Leave for work in. T minus 5 minutes."
          tts_pause_delay: '00:00:00'
      - service: script.entertainment_center_turn_off

# T-0m
  - alias: leave_for_work_t0m
    trigger:
      - platform: template
        value_template: >
          {% if states.sensor.now_hour.state| int == states.sensor.var_mike_leave_for_work_hour.state | int %}
            {% if states.sensor.now_minute.state | int == states.sensor.var_mike_leave_for_work_minute.state | int %}
              true
            {% endif %}
          {% endif %}
    condition:
      - condition: state
        entity_id: input_boolean.option_notify2_prework_timebased_lights
        state: 'on'
    action:
      - service: script.notify2
        data_template:
          flood_color: "red"
          entity_id: group.timebased_flood_lights
          delay: "00:00:01"
          tts_entity_id: group.tts_devices
          tts_sound: 'isaac/weapon_room.mp3'
          tts_sound_delay: '00:00:05'
          tts_message: "It's time to leave for work. Have a good day. Goodbye"
          tts_pause_delay: '00:00:00'
      # Turn On - Normal Mode
      - service: input_boolean.turn_on
        entity_id: input_boolean.option_mode_normal
      - service: script.entertainment_center_turn_off
      - service: script.computer_monitors_turn_off

##########################################
########## NOTIFICATIONS #################
##########################################



##########################################
########## AUTOMATIONS: MIKE OFF WORK ####
##########################################

  # Mike Off Work: T-1h
  - alias: mike_off_work_t1h
    trigger:
      - platform: template
        value_template: >
          {% if now().hour | int == states.sensor.var_mike_work_end_hour.state | int - 1 %}
            true
          {% endif %}
    condition:
      - condition: state
        entity_id: sensor.mike_at_work
        state: 'on'
      - condition: state
        entity_id: input_boolean.var_mike_home
        state: 'off'
    action:
      # Turn on Air Conditioner/Fans via Temp Control
      - condition: template
        value_template: '{% if  states.sensor.indoor_temperature.state  %}{% if states.sensor.indoor_temperature.state | float > states.sensor.indoor_temp_warm_level.state | float %}true{%endif%}{%endif%}'
      - condition: template
        value_template: '{% if  states.sensor.dark_sky_apparent_temperature.state  %}{% if states.sensor.dark_sky_apparent_temperature.state | int > 50 %}true{%endif%}{%endif%}'
      - service: input_boolean.turn_on
        entity_id: input_boolean.option_indoor_temp_hot

  # Mike Off Work: T-0h
  - alias: mike_off_work_t0h
    trigger:
      - platform: template
        value_template: >
          {% if now().hour | int == states.sensor.var_mike_work_end_hour.state | int  %}
            true
          {% endif %}
    condition:
      - condition: state
        entity_id: input_boolean.var_mike_home
        state: 'off'
    action:
      # Turn on Air Conditioner/Fans via Temp Control
      - condition: template
        value_template: '{% if  states.sensor.indoor_temperature.state  %}{% if states.sensor.indoor_temperature.state | float > states.sensor.indoor_temp_warm_level.state | float %}true{%endif%}{%endif%}'
      - condition: template
        value_template: '{% if  states.sensor.dark_sky_apparent_temperature.state  %}{% if states.sensor.dark_sky_apparent_temperature.state | int > 50 %}true{%endif%}{%endif%}'
      - service: input_boolean.turn_on
        entity_id: input_boolean.option_indoor_temp_hot


##########################################
########## AUTOMATIONS ###################
##########################################



##########################################
########## SCRIPTS #######################
##########################################
# script:





##########################################
########## STORED VARIABLES ##############
##########################################
# input_boolean:

##########################################
########## OPTIONS #######################
##########################################


##########################################
############### GROUPS ###################
##########################################
group:
  automation_work:
    entities:
      - automation.mike_at_work
      - automation.mike_not_at_work
      - automation.leave_for_work_t2h
      - automation.leave_for_work_t1h
      - automation.leave_for_work_t30m
      - automation.leave_for_work_t15m
      - automation.leave_for_work_t10m
      - automation.leave_for_work_t5m
      - automation.leave_for_work_t0m
      - automation.mike_off_work_t1h
      - automation.mike_off_work_t0h

  backend_work:
    entities:
      - sensor.mike_at_work
      - sensor.mike_work_day
      - input_boolean.var_mike_leave_for_work_timebased_lights_on

  hidden_work:
    entities:
      - sensor.var_mike_leave_for_work_hour
      - sensor.var_mike_leave_for_work_minute
      - sensor.var_mike_work_start_hour
      - sensor.var_mike_work_end_hour
      - sensor.var_mike_work_week_third_shift
      - sensor.var_mike_work_week
      - sensor.var_mike_work_week_third_shift_last_day

  # options_work:
  #   entities:

#   script_work:
#     entities:
#       - script.
