switch:
  - platform: mqtt
    name: sonoff_box_fan1
    command_topic: "cmnd/sonoff_2752/power"
    state_topic: "stat/sonoff_2752/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

automation:
  #********** Volume Adjustment ***************************************#
  - alias: fan_on_chromecast_volume_up
    trigger:
      - platform: state
        entity_id: switch.sonoff_small_desk_fan1
        state: 'on'
    condition:
      - condition: state
        entity_id: switch.sonoff_entertainment_center
        state: 'on'
    action:
      - service: script.set_entertainment_center_tv_volume
        data:
          volume_up: 2


  - alias: fan_off_chromecast_volume_down
    trigger:
      - platform: state
        entity_id: switch.sonoff_small_desk_fan1
        state: 'off'
    condition:
      - condition: state
        entity_id: switch.sonoff_entertainment_center
        state: 'on'
    action:
      - service: script.set_entertainment_center_tv_volume
        data:
          volume_down: 2


##########################################
############### GROUPS ###################
##########################################
group:
  automation_sonoff_box_fan1:
    entities:
      - automation.fan_on_chromecast_volume_up
      - automation.fan_off_chromecast_volume_down

  # script_sonoff_box_fan1:
  #   entities:
